### PR TITLE
ratbagctl: put the device node at the beginning of the command

### PR DESCRIPTION
**Pull request by bentiss**
See #635 for a full description, or the commit message

### CODE REVIEW

**Comment by bentiss** [comment]
Grmbl, and of course, we have tests to test the command line arguments, so they all fail.

**Comment by bentiss** [comment]
forced push with the tests fixed

**Comment by Hjdskes** [comment]
We also need to update documentation, such as the Wiki.

**Comment by bentiss** [comment]
> We also need to update documentation, such as the Wiki.

Aye!

**Comment by whot** [comment]
that's done now too btw

**Pull request merged**
