### PR TITLE
add SVG Logitech G303 data

### PR DESCRIPTION
**Pull request by alcomposer**
An SVG of the Logitech G303 mouse, can also pass as the G302 as very little difference between models

### CODE REVIEW

**Comment by alcomposer** [comment]
Ok, just realised that button 3 & 4 are lable wrong way around.

Will fix soon.

**Comment by alcomposer** [comment]
Not on my computer right now, and can't install Git, can't this happen auto now? 

http://stackoverflow.com/questions/35948131/github-squash-commits-from-web-interface-on-pull-request-after-review-comments

Otherwise I can later tonight.

**Comment by alcomposer** [comment]
Hey @bentiss, let me know if the squash is ok.

**Comment by bentiss** [comment]
I don't think the squash you did is correct. You should have had only one commit on top of the common branch, not 2. I'll try the squash and merge feature of github on my side.

**Comment by alcomposer** [comment]
Yeah, I think I did it right the first time, but then messed up something... Git is newish to me... :-(

**Comment by bentiss** [comment]
No worries. We all need to learn the process at some point. The good thing is that the squash and merge feature (that was disable before by me) seems to do the job properly. So we are good now :)

I disabled it to prevent aggressive squash and merges, but it seems that in such cases it's a good feature.

**Pull request merged**
