### PR TITLE
data: add a fallback.svg file

### PR DESCRIPTION
**Pull request by whot**
This SVG is generic enough to cover 7-button mice with up to 3 LEDs that are
supported but don't have an SVG. The SVG style is intentionally NOT a generic
mouse to make it obvious that something isn't right here. If we use a generic
mouse, people may not put the effort into a proper SVG style because the
generic mouse is good enough.

The fallback is currently only used for test devices

### CODE REVIEW

**Comment by Hjdskes** [comment]
Hah, I love it. I'm merging this now, we can discuss the default SVG in #307.

**Comment by whot** [comment]
Note: updated with the commit to always supply the fallback.svg from ratbagd if libratbag returns NULL.

**Comment by bentiss** [comment]
Looks like you forgot to remove the fallback on the test-device (at least, this is what written on the commit)

**Comment by whot** [comment]
oops, fixed and force-pushed. that was an old commit message, removing the fallback in the test device gives us an error every time on startup which isn't pretty

**Comment by Hjdskes** [comment]
@bentiss things look good to me, leaving this one up to you to merge.

**Comment by whot** [comment]
ask for forgiveness, not for permission. so I'm merging this now :)

**Pull request merged**
