### PR TITLE
ci: add arch

### PR DESCRIPTION
**Pull request by FFY00**

### CODE REVIEW

**Comment by FFY00** [comment]
I don't understand why ratbagctl-test isn't being skipped. It expects a file that is only present after instalation.

@whot, any ideas?

**Comment by whot** [comment]
looks good, but I wonder why the CI failed. Can you double-check that please?

**Comment by FFY00** [comment]
Acording to meson's documentation the executable should exit with code `77` so it gets marked as skipped. They dond't mention any alternnative on why a test would be marked as skipped.

http://mesonbuild.com/Unit-tests.html#skipped-tests

**Comment by FFY00** [comment]
Can someone look into this? Whe building libratbag on a clean chroot, the test is skipped. Don't know why the same behavior isn't present here.

**Comment by FFY00** [comment]
Shouldn't that be handled by the test?

**Comment by FFY00** [comment]
Well that had something to do with it. Now the test is timming out.

**Comment by whot** [comment]
maybe the dbus service doesn't start? or is otherwise restricted? Not sure but you should be able to reproduce this locally with a docker image, just run the same commands and see if it works out.

**Comment by FFY00** [comment]
The dbus service should already be running.

https://www.archlinux.org/news/d-bus-now-launches-user-buses/

**Comment by FFY00** [comment]
I'll deal with this tomorrow.

**Comment by FFY00** [comment]
Here's whats going wrong:
```
ratbagd.devel error: Failed to start ratbagd: Permission denied
```

**Comment by FFY00** [comment]
@whot can you give me access to circleci? Specifically SSH permissions so that I can debug this issue?

**Comment by whot** [comment]
I honestly can't figure out how to do that. You don't show up anywhere in CircleCI (others like phomes do when I click on the invite link). Can you see libratbag in https://circleci.com/add-projects? Maybe you need to create a CircleCI account (or log in with github) once to be known to the system?

Have you tried the local docker approach? that may also be able to reproduce the issue

**Comment by FFY00** [comment]
Probably because I am not in the organization? I tried running the circleci cli tool but that doesn't seem to allow us to interact with the build.

**Comment by whot** [comment]
yep, that was it. you were in libratbag but not in the org.

**Comment by FFY00** [comment]
So, it looks like https://github.com/libratbag/libratbag/blob/23ff4e753d68267096ea66e729337bb3653fc650/ratbagd/ratbagd.c#L553 is being triggered. No clue why. Need to do some debugging.

**Pull request closed without merging**
