### PR TITLE
fixed G304

### PR DESCRIPTION
**Pull request by adarshsingh87**

### CODE REVIEW

**Comment by FFY00** [comment]
You also have to have an entry in the `meson.build` file.

**Comment by FFY00** [comment]
Looks like the G304 is the same as the G305. We already have a device file for this ID, is it not showing in your machine?

**Comment by adarshsingh87** [comment]
it shows up as g305 rather than g304

**Comment by FFY00** [comment]
The devices have the same ID, and seem the same. We can only have one name.

**Pull request closed without merging**
