### PR TITLE
Release script fixes (for piper, mainly)

### PR DESCRIPTION
**Pull request by whot**
hand-composing stuff is boring, let's re-use the script

### CODE REVIEW

**Comment by whot** [comment]
FTR, this is a copy of the xorg `release.sh` script and it's only run by maintainers for releases. I'd say that as long as it's good enough it'll do the job, but if you do make changes, making it for the upstream script too would be very appreciated. Also note, the upstream script at least has to run on different platforms which may explain a few things...

https://gitlab.freedesktop.org/xorg/util/modular/

**Comment by FFY00** [comment]
You use `/bin/bash` ion the shebang instead of `/bin/sh` so we can make use of bash specific features. Can I assume GNU's coreutils or is it supposed to be full posix compliant?

**Comment by whot** [comment]
for libratbag? linux-only, basically, so assume whatever a sensible baseline is (we use glib and libsystemd already, so...)

for the upstream one? I think that one has to work on openbsd in bad weather when the moon is in the house of aquarius. Which is basically why no-one wants to touch it.

**Comment by FFY00** [comment]
Then perhaps you should drop the bash dependency and make it full posix compliant, shell + commands.

**Comment by whot** [comment]
lol. I just went "what, this uses bash??" and then found that it was me who changed it to bash 5 years ago, with exactly the argument of "bugger that, too complicated to support sh".

So go for it, add whatever bashism you want. GNU coreutils - don't know, but let's see if anyone complains.

**Pull request merged**
