### PR TITLE
data: add Logitech M545

### PR DESCRIPTION
**Pull request by matt-hu**

### CODE REVIEW

**Comment by FFY00** [comment]
Did you test it? Is it working as expected?

**Comment by matt-hu** [comment]
@FFY00 Everything is working as expected, here is what I have tested:

- Detected by ratbagd
- Listed when running `ratbagctl list`
- Detected by piper (haven't got round to making an svg yet)
- Able to change settings in piper

**Comment by FFY00** [comment]
Great, thanks!

**Review by FFY00 — CHANGES_REQUESTED** [review]
Could please remove the `meson_options-backups/meson_options-2020-12-26_134423.zip` file you probably accidentally added to git? Thanks :blush:

**Comment by matt-hu** [comment]
@FFY00 Sorry about that! All done.

**Review by FFY00 — APPROVED** [review]

**Pull request merged**
