### PR TITLE
HID++ 2.0: Support non gaming mice again

### PR DESCRIPTION
**Pull request by bentiss**
We used to support them, but they are kind of crashing. Kind of fixing them then.

### CODE REVIEW

**Comment by whot** [comment]
the second patch looks ok, but I'm not sure we want the first one - why do we need to support the devices  if they're clearly not meeting the requirements we have?

**Comment by bentiss** [comment]
> why do we need to support the devices if they're clearly not meeting the requirements we have?

The reason is that if you happen to have one of these mouse connected to your system, libratbag (or ratbagd) will fail to start given that the assert will be raised.
An other solution would be to blacklist or whitelist Logitech devices, but this is maybe not something we want. Actually, we could require feature 0x8100 to be present, but given the MX Master can have the DPI changed, I still think we should support it somehow.

**Comment by whot** [comment]
uhm, what's the status of this? sorry , I lost track, but is this waiting on me to click the merge button?

**Comment by bentiss** [comment]
> uhm, what's the status of this? sorry , I lost track,

It is still needed AFAICT. I can not reproduce the assert which kills ratbagds, but the MX master requires it if we want to configure it.

>  but is this waiting on me to click the merge button?

Pretty much, yes.

**Comment by r00tbox** [comment]
I switched back to the master, and hope this gets merged into the master soon, so i can use my MX Master again.

**Comment by whot** [comment]
Done, thanks for testing

**Pull request merged**
