### PR TITLE
data: add G915 TKL

### LINKED ISSUE #1008: Logitech G915 TKL is not recognized
**Is your feature request related to a problem? Please describe.**

Logitech G915 TKL is not recognized ratbagctl (from ratbagd 0.13-1 which is part of Ubuntu 20.04). It's the new (released June 2020) smaller version of full size G915. It seems like G915 is recognized, judging by presence of /usr/share/libratbag/logitech-g915.device (also read that it was added to libratbag).

**Describe the solution you'd like**

Would like for G915 TKL to be recognized (all connections: lightspeed, bluetooth, wired) and to be able to set LEDs etc.

**Describe alternatives you've considered**

Tried lightspeed and wired connections, ran ratbagctl with and without sudo. None of those help.

**Additional context**

Output of ratbagctl (I do have MX Master 2S connected via bluetooth):

```
$ ratbagctl list
hooting-chinchilla:  MX Master 2S           
```         

When I connect the keyboard via USB cable I get following /var/log/syslog messages:
```
Jun 12 01:33:49 jozinko kernel: [12280.948661] usb 1-2: new full-speed USB device number 14 using xhci_hcd
Jun 12 01:33:49 jozinko kernel: [12281.100717] usb 1-2: New USB device found, idVendor=046d, idProduct=c343, bcdDevice=14.00
Jun 12 01:33:49 jozinko kernel: [12281.100725] usb 1-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Jun 12 01:33:49 jozinko kernel: [12281.100729] usb 1-2: Product: G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard
Jun 12 01:33:49 jozinko kernel: [12281.100732] usb 1-2: Manufacturer: Logitech
Jun 12 01:33:49 jozinko kernel: [12281.100735] usb 1-2: SerialNumber: BA346238
Jun 12 01:33:49 jozinko kernel: [12281.107039] input: Logitech G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard as /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.0/0003:046D:C343.000E/input/input41
Jun 12 01:33:49 jozinko kernel: [12281.169801] hid-generic 0003:046D:C343.000E: input,hidraw0: USB HID v1.11 Keyboard [Logitech G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard] on usb-0000:00:14.0-2/input0
Jun 12 01:33:49 jozinko kernel: [12281.171862] input: Logitech G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard Mouse as /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.1/0003:046D:C343.000F/input/input42
Jun 12 01:33:49 jozinko kernel: [12281.228990] input: Logitech G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard Consumer Control as /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.1/0003:046D:C343.000F/input/input43
Jun 12 01:33:49 jozinko kernel: [12281.229368] input: Logitech G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard System Control as /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.1/0003:046D:C343.000F/input/input44
Jun 12 01:33:49 jozinko kernel: [12281.229782] hid-generic 0003:046D:C343.000F: input,hidraw1: USB HID v1.11 Mouse [Logitech G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard] on usb-0000:00:14.0-2/input1
Jun 12 01:33:49 jozinko kernel: [12281.231341] hid-generic 0003:046D:C343.0010: hiddev0,hidraw2: USB HID v1.11 Device [Logitech G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard] on usb-0000:00:14.0-2/input2
```

### PR DESCRIPTION
**Pull request by FFY00**
Closes #1008

Signed-off-by: Filipe Laíns <lains@archlinux.org>

### CODE REVIEW

**Review by conrad82 — APPROVED** [review]
Can confirm usb address works for G915 TKL

**Comment by jpbartolomeo** [comment]
Hi. I got a Logitech G915 (no TKL). If I connect with USB, it`s detected ok, but not with bluetooth.
I follow the change of the commit and I`ve changed:

DeviceMatch=usb:046d:c343
with:
DeviceMatch=usb:046d:c343;bluetooth:046d:b35f

I put that number because this is the output of "bluetoothctl":
Modalias: usb:v046DpB354d0035

After the change, I restart the service but the keyboard is still not detected. Any suggestions?

Thanks!

**Comment by FFY00** [comment]
That looks correct! Could you open a PR?

**Comment by jpbartolomeo** [comment]
Sorry. I guess that PR is Pull Request hahahaha. I'm Software Engineer, butI don't know how to proceed here hahahahah. What info do you need in the PR?

**Pull request merged**
