### PR TITLE
Correct G403 ID. Added Wireless-specific G403 device file.

### LINKED ISSUE #384: Logitech G403 hardware ID not correct
[data/devices/logitech-g403.device](https://github.com/libratbag/libratbag/blob/master/data/devices/logitech-g403.device) reports the Logitech G403 ID as `046d:c082` when in reality it is `046d:c083`

### PR DESCRIPTION
**Pull request by JoshStrobl**
Resolves #384. Confirmed [under Solus](https://dev.solus-project.com/R3780:07a0590216760778cfd272f40fc79d17f7325ac9) while packaging.

### CODE REVIEW

**Comment by whot** [comment]
cc @gicmo, can you confirm this please? Do we need to add or change the c082 entry?

**Comment by gicmo** [comment]
I think there are two versions of the G403: one wired and one wireless. Maybe they have different ids. I have the wireless one that can optionally be connected via a cable and if so connected it reports as **`046d:c082`**:
```
Bus 001 Device 002: ID 046d:c082 Logitech, Inc. 
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x046d Logitech, Inc.
  idProduct          0xc082 
  bcdDevice            3.01
  iManufacturer           1 Logitech
  iProduct                2 G403 Prodigy Wired/Wireless Gaming Mouse
  iSerial                 3 056736663634
  bNumConfigurations      1

```

**Comment by Hjdskes** [comment]
I can confirm that wired it has 046D:C082, wirelessly it gives me 046D:C539 though.

**Comment by gicmo** [comment]
@Hjdskes yeah, that is the dongle which is also used by others, e.g. the [G900](https://github.com/libratbag/libratbag/blob/master/data/devices/logitech-g900-wireless.device)

**Comment by JoshStrobl** [comment]
@Hjdskes Yes and mine doesn't report with C082 and mine is wired.

**Comment by Hjdskes** [comment]
So @gicmo is right in that there are two versions then; it seems him and I have the wireless version that can optionally be connected via cable and @JoshStrobl has the other, wired-only version.

**Comment by bentiss** [comment]
> Maybe we should have a device file for Logitech G403 (Wireless)?

Yes, exactly. Sorry I have been busy the past 2 weeks, and I couldn't dive into this bug (I have an email from Logitech saying exactly that the G403 has 2 different PID while using the cord, depending of the version).

Please update the PR (force push) by moving the current `logitech-g403.device` file into `logitech-g403-wireless.device`, and adding the modified file you changed as is.

**Comment by JoshStrobl** [comment]
Will do.

**Comment by JoshStrobl** [comment]
I wasn't sure if you wanted me to change the name in the wireless device file so I left it as is. Not a problem if I need to change it.

**Comment by whot** [comment]
fwiw, the `DeviceMatch` line supports multiple matches, so for devices that are identical we should use `DeviceMatch=usb:1234:abcd;bluetooth:5678:aaaa` (semicolon-separated list). @JoshStrobl mind submitting a PR to de-duplicate this again? Thanks

**Comment by JoshStrobl** [comment]
@whot Before I go about implementing it, does it support multiple usb IDs in addition to bluetooth, or just usb+bluetooth?

**Comment by whot** [comment]
@JoshStrobl yeah, it'll support multiple USB matches too, the above was just an example to include bluetooh.

**Comment by JoshStrobl** [comment]
Sorry for the delay, been busy with other stuff. I'll get a PR sent in tonight.

**Pull request merged**
