### PR TITLE
Add Logitech G903 wired configuration

### PR DESCRIPTION
**Pull request by Nefelim4ag**

### CODE REVIEW

**Comment by Nefelim4ag** [comment]
I can't get wireless configuration, libratbad not see mouse.

**Comment by FFY00** [comment]
The wireless connector probably has a different device ID.

**Comment by Nefelim4ag** [comment]
```
➜  ~ lsusb | grep Logi
Bus 001 Device 003: ID 046d:c539 Logitech, Inc. 
Bus 001 Device 044: ID 046d:c086 Logitech, Inc. 
```

**Comment by FFY00** [comment]
Try to add another file for that ID, should work.

**Comment by FFY00** [comment]
Do you have both connectors connected?

**Comment by Nefelim4ag** [comment]
@FFY00, i can connect both at same time if needed =)

**Comment by Hjdskes** [comment]
I forgot, do you need to reload ratbagd when you change the device files?

**Comment by FFY00** [comment]
That's what I thought that might be causing this :smile:.

**Comment by Nefelim4ag** [comment]
I've fresh boot system, can't even get that working in 100% cases.
I try plug/unplug dongle several times:
```
➜  ~ sudo ratbagd --verbose
ratbag debug: Logitech USB Receiver Mouse is device '/dev/hidraw0'.
ratbag debug: Logitech USB Receiver Mouse is device '/dev/hidraw1'.
ratbag debug: report ID 02
ratbag debug: report ID 03
ratbag debug: report ID 04
ratbag debug: report ID 08
ratbag debug: Logitech USB Receiver Mouse is device '/dev/hidraw2'.
ratbag debug: report ID 10
ratbag debug: report ID 11
ratbag debug: report ID 20
ratbag debug: report ID 21
ratbag debug: 'Logitech USB Receiver Mouse' is using protocol v4.2
ratbag debug: device has adjustable dpi
ratbag debug: device is at 1200 dpi (variable between 50 and 12000).
ratbag debug: device has adjustable report rate
ratbag debug: device has 4 report rates
ratbag debug: device has onboard profiles
ratbag debug: device has configurable mouse button spy
ratbag debug: device has color effects
ratbag debug: device has non-rgb leds
ratbag debug: driver match found: Logitech HID++2.0
event8: "Logitech USB Receiver Mouse", 5 profiles
ratbag debug: Logitech USB Receiver Mouse is device '/dev/hidraw0'.
ratbag debug: Logitech USB Receiver Mouse is device '/dev/hidraw1'.
ratbag debug: report ID 02
ratbag debug: report ID 03
ratbag debug: report ID 04
ratbag debug: report ID 08
ratbag debug: Logitech USB Receiver Mouse is device '/dev/hidraw2'.
ratbag debug: report ID 10
ratbag debug: report ID 11
ratbag debug: report ID 20
ratbag debug: report ID 21
ratbag debug:     HID++ error from the device (1): ERR_UNSUPPORTED (09)
ratbag debug: Logitech USB Receiver Mouse is device '/dev/hidraw0'.
ratbag debug: Logitech USB Receiver Mouse is device '/dev/hidraw1'.
ratbag debug: report ID 02
ratbag debug: report ID 03
ratbag debug: report ID 04
ratbag debug: report ID 08
ratbag debug: Logitech USB Receiver Mouse is device '/dev/hidraw2'.
ratbag debug: report ID 10
ratbag debug: report ID 11
ratbag debug: report ID 20
ratbag debug: report ID 21
ratbag debug: 'Logitech USB Receiver Mouse' is using protocol v4.2
ratbag debug: device has adjustable dpi
ratbag debug: device is at 1200 dpi (variable between 50 and 12000).
ratbag debug: device has adjustable report rate
ratbag debug: device has 4 report rates
ratbag debug: device has onboard profiles
ratbag debug: device has configurable mouse button spy
ratbag debug: device has color effects
ratbag debug: device has non-rgb leds
ratbag debug: driver match found: Logitech HID++2.0
event8: "Logitech USB Receiver Mouse", 5 profiles
ratbag debug: Logitech USB Receiver Mouse is device '/dev/hidraw0'.
ratbag debug: Logitech USB Receiver Mouse is device '/dev/hidraw1'.
ratbag debug: report ID 02
ratbag debug: report ID 03
ratbag debug: report ID 04
ratbag debug: report ID 08
ratbag debug: Logitech USB Receiver Mouse is device '/dev/hidraw2'.
ratbag debug: report ID 10
ratbag debug: report ID 11
ratbag debug: report ID 20
ratbag debug: report ID 21
ratbag debug: 'Logitech USB Receiver Mouse' is using protocol v4.2
ratbag debug: device has adjustable dpi
ratbag debug: device is at 1200 dpi (variable between 50 and 12000).
ratbag debug: device has adjustable report rate
ratbag debug: device has 4 report rates
ratbag debug: device has onboard profiles
ratbag debug: device has configurable mouse button spy
ratbag debug: device has color effects
ratbag debug: device has non-rgb leds
ratbag debug: driver match found: Logitech HID++2.0
event8: "Logitech USB Receiver Mouse", 5 profiles
ratbag debug: Logitech USB Receiver Mouse is device '/dev/hidraw0'.
ratbag debug: Logitech USB Receiver Mouse is device '/dev/hidraw1'.
ratbag debug: report ID 02
ratbag debug: report ID 03
ratbag debug: report ID 04
ratbag debug: report ID 08
ratbag debug: Logitech USB Receiver Mouse is device '/dev/hidraw2'.
ratbag debug: report ID 10
ratbag debug: report ID 11
ratbag debug: report ID 20
ratbag debug: report ID 21
ratbag debug:     HID++ error from the device (1): ERR_UNSUPPORTED (09)
```

**Comment by Nefelim4ag** [comment]
So, no new wireless config needed.

**Comment by whot** [comment]
well, if that's not a ringing endorsement, I don't know what is... :)

**Pull request merged**
