### PR TITLE
fix meson complaints

### PR DESCRIPTION
**Pull request by whot**
meson git master added warnings for the places where unsupported keywords are in use. And we were using them (outrageous, I know!), so here's a PR to remove the warning. Because there's already enough shouting going on in the world, we don't need more from meson.

### CODE REVIEW

**Comment by bentiss** [comment]
Care to add valgrind in circle.yml in both fedora and ubuntu setups so that the CI still works???

Thanks :)

**Comment by whot** [comment]
done. tests are all happy now

**Comment by bentiss** [comment]
Quick question (merging this anyway), don't we want to trigger the valgrind test in the CI too? Or is tat only doable with actual hardware?

**Comment by bentiss** [comment]
Aargh, I tried using the "fix conflicts" feature, and it seems it made some bullshit in the PR. I'll manually apply it.

**Comment by whot** [comment]
For the valgrind test, we'd need a separate command: `mesontest --setup=valgrind` to be run in the build directory. It does the same as the normal test, so if the normal test works, valgrind should too.

**Pull request closed without merging**
