### PR TITLE
ratbagd: use libunistring to convert profile names to utf-8

### PR DESCRIPTION
**Pull request by whot**
@YoyPa does this one work for your crazy profile names? In theory it should, but... well... :)

### CODE REVIEW

**Comment by FFY00** [comment]
Probably should update the CI to install it :P

**Comment by whot** [comment]
/me mumbles something about stupid tests :)

**Comment by YoyPa** [comment]
It doesn't crash and let me rename profile to less crazy things :).
But it give some weird output if I play with it:
```
# yo @ yo-gs in ~ [23:38:12] 
$ ratbagctl warbling-mara profile 4 name set ₣°æ§ï

# yo @ yo-gs in ~ [23:39:11] 
$ ratbagctl warbling-mara profile 4 name get      
â£Â°Ã¦Â§Ã¯

# yo @ yo-gs in ~ [23:39:16] 
$ ratbagctl warbling-mara profile 4 name set "profile n° 1"

# yo @ yo-gs in ~ [23:40:04] 
$ ratbagctl warbling-mara profile 4 name get               
profile nÂ° 1
```
I love how the french franc (₣) symbol is replaced by GB pound (£) :rofl: 
PS: sorry for the late answer :innocent:

**Comment by whot** [comment]
Right, turns out blindly converting from latin isn't a smart thing to do once we write a utf8 string and it's better to just check for valid utf8 first :) Please try the current branch, that should work now.

**Comment by YoyPa** [comment]
It's a perfect for me:
```
# yo @ yo-gs in ~/Documents/git/libratbag on git:wip/utf8-support x [18:36:58] 
$ ratbagctl warbling-mara profile 4 name set ₣°æ§ï         

# yo @ yo-gs in ~/Documents/git/libratbag on git:wip/utf8-support x [18:37:08] 
$ ratbagctl warbling-mara profile 4 name get      
₣°æ§ï
```

**Comment by whot** [comment]
pushed a minor cleanup, ready for review now

**Pull request merged**
