### PR TITLE
Add Logitech G900 SVG for gnome theme

### PR DESCRIPTION
**Pull request by cvuchener**
Related issues: #300, #213.

@kudlatyamroth or @kaymio please test this.

### CODE REVIEW

**Comment by bentiss** [comment]
Thanks for the SVG.

Couple of issues:
- you are missing:
```
diff --git a/meson.build b/meson.build
index c4f104b..4bb8755 100644
--- a/meson.build
+++ b/meson.build
@@ -280,6 +280,7 @@ gnome_svg_files = [
        'data/gnome/logitech-g500s.svg',
        'data/gnome/logitech-g502.svg',
        'data/gnome/logitech-g700.svg',
+       'data/gnome/logitech-g900.svg',
        'data/gnome/roccat-kone-xtd.svg',
 ]
 install_data(gnome_svg_files,
```
- all the texts that are supposed to be shown on right are aligned from the left (so they are overlapping with the leader instead of moving out from it)

**Comment by bentiss** [comment]
And some more information:
- you need to use `style="text-align:start...` instead of `style="text-align:end...`
- the LED are inverted, and you can not really configure the LED that show the DPI/profile (right under the resolution up/down buttons). So I'd remove the second LED and keep only the logo one as LED-0

**Comment by cvuchener** [comment]
I knew I forgot something. Is it good now?

**Comment by cvuchener** [comment]
I missed your message about the LEDs. I changed that too, now.

**Pull request merged**
