### PR TITLE
Create logitech-g502-spectrum.device

### PR DESCRIPTION
**Pull request by matt24smith**
Adding support for my mouse

### CODE REVIEW

**Comment by FFY00** [comment]
Please add it to `meson.build` too.

**Comment by cvuchener** [comment]
g502 proteus spectrum is here: https://github.com/libratbag/libratbag/blob/master/data/devices/logitech-g502-proteus-spectrum.device

Yours has a Holtek vendor id. What is it?

**Comment by FFY00** [comment]
Hum, what? A knockoff?

**Comment by cvuchener** [comment]
I think it may be a keyboard:

https://antoinealb.net/2014/12/05/archlinux-install.html

> To do this, first use lsusb to find the device ID. For example for my WASD keyboard the relevant line is :
>
> > Bus 001 Device 006: ID 04d9:0169 Holtek Semiconductor, Inc.
>
> and the device ID here is 04d9:0169.

**Comment by FFY00** [comment]
Yeah, takes makes more sense. @matt24smith you probably got the wrong id. Are you sure the latest release doesn't work?

**Comment by matt24smith** [comment]
Yes you're right actually. The library wasn't working for me until after I created the file so I mistakenly thought I had fixed the issue with it. It appears to be working correctly now without the file I created. My mistake. 
Thanks for the quick response!

**Pull request closed without merging**
