### PR TITLE
Switch to a flat probe() function instead of the callbacks

### PR DESCRIPTION
**Pull request by whot**
Note: this builds on #368

### CODE REVIEW

**Comment by whot** [comment]
Rebased and force-pushed, thanks

**Comment by phomes** [comment]
I have tested with the logitech G300. LGTM

**Comment by phomes** [comment]
and tested with G9 (HID++1.0). It works fine there as well with a patch to fix up an unrelated issue.

**Comment by bentiss** [comment]
OK, then I consider this to be enough. If G-Skill breaks, we'll hear it one way or one other.

**Pull request merged**
