### PR TITLE
Logo enhancements

### PR DESCRIPTION
**Pull request by bentiss**
- Add RGB lighting
- use the logo on the README
- use the logo on the produced DBus API documentation

### CODE REVIEW

**Comment by whot** [comment]
good lord, it's like like the internet in 1999....

**Comment by bentiss** [comment]
> If we want a logo like this that changes colours, we'll have to integrate it properly to create something that has a led-like thing (maybe the rat's eyes or the tail?) instead of just painting the rats in color. Sorry.

No worries. Pushed a new commit to only animate the eyes. It makes the whole thing less distracting

**Comment by whot** [comment]
lol

**Comment by bentiss** [comment]
FYI, I used my admin skills to push a quick update on the readme to use the animated one, and to make it bigger. I like the final result :)

**Comment by Hjdskes** [comment]
Oh yes, it's awesome!

**Pull request merged**
