### PR TITLE
sinowealth: enable additional profiles if specified in the device file

### PR DESCRIPTION
**Pull request by staticssleever668**

### CODE REVIEW

**Comment by staticssleever668** [comment]
@kierprev, hi, this adds the second profile support for your mouse. Could you try it?

**Comment by KierPrev** [comment]
> @KierPrev, hi, this adds the second profile support for your mouse. Could you try it?

Yes. Can I overwrite the installation by compiling it again from the updated source?

**Comment by staticssleever668** [comment]
Yes.

**Comment by KierPrev** [comment]
I did it.
How do I tell if it worked?

**Comment by staticssleever668** [comment]
It should show it.
Did you install libratbag the same way as before?

**Comment by KierPrev** [comment]
Where? 


`Did you install libratbag the same way as before?`

Exactly the same way:

```
git clone https://github.com/libratbag/libratbag.git
cd libratbag
meson builddir
ninja -C builddir
sudo ninja -C builddir install
sudo systemctl restart --now ratbagd.service
```

**Comment by staticssleever668** [comment]
It should display in the upper left corner, like so:
image

---

Bizarre, what do `command -v ratbagd` and `sudo systemctl stop ratbagd.service && sudo ratbagd --verbose` say?

**Comment by staticssleever668** [comment]
Oh, I think you need to run `sudo cp /usr/local/lib/x86_64-linux-gnu/systemd/ratbagd.service /usr/lib/systemd/system/ratbagd.service` again, since I updated installation path for ratabgd in #1443

**Comment by KierPrev** [comment]
Ahm, after copying the file, and restarting the service, it still doesn't show up, as in your screenshot.

**Comment by staticssleever668** [comment]
> Oh, I think you need to run `sudo cp /usr/local/lib/x86_64-linux-gnu/systemd/ratbagd.service /usr/lib/systemd/system/ratbagd.service` again, since I updated installation path for ratabgd in #1443

Also, you will probably now have old libratbag executables installed in the old path, so you should do `sudo rm /usr/bin/lur-command /usr/bin/ratbagctl /usr/bin/ratbagd` to get rid of them.

**Comment by KierPrev** [comment]
```
rm: cannot remove '/usr/bin/lur-command': No such file or directory
rm: cannot remove '/usr/bin/ratbagctl': No such file or directory
rm: cannot remove '/usr/bin/ratbagd': No such file or directory

```

**Comment by staticssleever668** [comment]
Oh so you installed libratbag with the patch already installed, it's good! :+1: 
Would you try `command -v ratbagd` and `sudo systemctl stop ratbagd.service && sudo ratbagd --verbose` still?

**Comment by KierPrev** [comment]
Well, that's great and all. You did it!

Glad to help

**Comment by staticssleever668** [comment]
Thank you for letting me take some of your time, I'm grateful :)

**Comment by KierPrev** [comment]
It's funny to help some random people on the internet that you will never met

**Comment by staticssleever668** [comment]
Oof I merged with a fixup commit in, I'll be more careful from now on

**Pull request merged**
