### PR TITLE
Adding new device identifier for the white G915 TKL

### PR DESCRIPTION
**Pull request by kevinkga**

### CODE REVIEW

**Review by stephanlachnit — APPROVED** [review]
@FFY00 can you merge this? ID confirmed in https://github.com/libratbag/piper/issues/599#issuecomment-737282513

**Comment by FFY00** [comment]
I am almost certain that is a receiver. The `c5` prefix should be reserved for receivers. So, same as #1071. I can confirm with Logitech and see if this receiver has the same problem as the one in #1071, which probably has.

**Comment by kevinkga** [comment]
> ~@FFY00 can you merge this?~ ID confirmed in [libratbag/piper#599 (comment)](https://github.com/libratbag/piper/issues/599#issuecomment-737282513)
> 
> @kevinkga have you tested this? Can you describe a bit what `ratbagctl` exposes and if the features work?

yes seems to work fine so far. Been using it for a few weeks now.
`cheering-viscacha - Logitech USB Receiver
             Model: usb:046d:c545:0
 Number of Buttons: 15
    Number of Leds: 2
Number of Profiles: 3
Profile 0: (active)
  Name: n/a
  Report Rate: 1000Hz
  Button: 0 is mapped to macro '↕F1'
  Button: 1 is mapped to macro '↕F2'
  Button: 2 is mapped to macro '↕F3'
  Button: 3 is mapped to macro '↕F4'
  Button: 4 is mapped to macro '↕F5'
  Button: 5 is mapped to macro '↕F6'
  Button: 6 is mapped to macro '↕F7'
  Button: 7 is mapped to macro '↕F8'
  Button: 8 is mapped to macro '↕F9'
  Button: 9 is mapped to macro '↕F10'
  Button: 10 is mapped to macro '↕F11'
  Button: 11 is mapped to macro '↕F12'
  Button: 12 is mapped to 'unknown'
  Button: 13 is mapped to 'unknown'
  Button: 14 is mapped to 'unknown'
  LED: 0, depth: rgb, mode: cycle, duration: 5000, brightness: 255
  LED: 1, depth: rgb, mode: cycle, duration: 5000, brightness: 255
Profile 1: (disabled)
Profile 2: (disabled)
`

**Comment by stephanlachnit** [comment]
@FFY00 is there a possible workaround for this? Else we maybe could add a "generic Logitech device" device file, which includes the receiver IDs (if that doesn't break something else). Not a pretty solution though.

**Comment by FFY00** [comment]
The fix for this is adding support for the receiver to the kernel driver, which will then export the device to userspace with the internal device ID instead of the receiver ID.

**Comment by whot** [comment]
Closing as per https://github.com/libratbag/libratbag/pull/1099#issuecomment-886113261, we can't add the receivers to libratbag

**Pull request closed without merging**
