### PR TITLE
Add support to Logitech G733

### PR DESCRIPTION
**Pull request by mtayllan**
Led works! I can change colors, mode, duration and brightness. 
Buttons dont work, always point to UNKNOW as see above:
```
screaming-acouchy - Logitech G733 Gaming Headset
             Model: usb:046d:0ab5:0
 Number of Buttons: 8
    Number of Leds: 2
Number of Profiles: 1
Profile 0: (active)
  Name: n/a
  Button: 0 is mapped to UNKNOWN
  Button: 1 is mapped to UNKNOWN
  Button: 2 is mapped to UNKNOWN
  Button: 3 is mapped to UNKNOWN
  Button: 4 is mapped to UNKNOWN
  Button: 5 is mapped to UNKNOWN
  Button: 6 is mapped to UNKNOWN
  Button: 7 is mapped to UNKNOWN
  LED: 0, depth: rgb, mode: cycle, duration: 5000, brightness: 0
  LED: 1, depth: rgb, mode: cycle, duration: 10000, brightness: 0
```

Number of buttons is wrong. The device only have 2 buttons and a volume scroll. 

As mentioned in #1021, the output of hid-recorder is:
```
# Logitech G733 Gaming Headset
# 0x05, 0x0c,                    // Usage Page (Consumer Devices)       0
# 0x09, 0x01,                    // Usage (Consumer Control)            2
# 0xa1, 0x01,                    // Collection (Application)            4
# 0x85, 0x01,                    //  Report ID (1)                      6
# 0x09, 0xe9,                    //  Usage (Volume Up)                  8
# 0x09, 0xea,                    //  Usage (Volume Down)                10
# 0x75, 0x01,                    //  Report Size (1)                    12
# 0x95, 0x02,                    //  Report Count (2)                   14
# 0x15, 0x00,                    //  Logical Minimum (0)                16
# 0x25, 0x01,                    //  Logical Maximum (1)                18
# 0x81, 0x02,                    //  Input (Data,Var,Abs)               20
# 0x75, 0x06,                    //  Report Size (6)                    22
# 0x95, 0x01,                    //  Report Count (1)                   24
# 0x81, 0x03,                    //  Input (Cnst,Var,Abs)               26
# 0x75, 0x18,                    //  Report Size (24)                   28
# 0x81, 0x03,                    //  Input (Cnst,Var,Abs)               30
# 0xc0,                          // End Collection                      32
# 0x05, 0x0b,                    // Usage Page (Telephony Devices)      33
# 0x09, 0x01,                    // Usage (Phone)                       35
# 0xa1, 0x01,                    // Collection (Application)            37
# 0x85, 0x08,                    //  Report ID (8)                      39
# 0x09, 0x2f,                    //  Usage (Phone Mute)                 41
# 0x75, 0x01,                    //  Report Size (1)                    43
# 0x81, 0x06,                    //  Input (Data,Var,Rel)               45
# 0x09, 0x20,                    //  Usage (Hook Switch)                47
# 0x81, 0x06,                    //  Input (Data,Var,Rel)               49
# 0x75, 0x06,                    //  Report Size (6)                    51
# 0x81, 0x03,                    //  Input (Cnst,Var,Abs)               53
# 0xc0,                          // End Collection                      55
# 0x06, 0x43, 0xff,              // Usage Page (Vendor Usage Page 0xff43) 56
# 0x0a, 0x02, 0x02,              // Usage (Vendor Usage 0x202)          59
# 0xa1, 0x01,                    // Collection (Application)            62
# 0x85, 0x11,                    //  Report ID (17)                     64
# 0x95, 0x13,                    //  Report Count (19)                  66
# 0x75, 0x08,                    //  Report Size (8)                    68
# 0x26, 0xff, 0x00,              //  Logical Maximum (255)              70
# 0x09, 0x02,                    //  Usage (Vendor Usage 0x02)          73
# 0x81, 0x00,                    //  Input (Data,Arr,Abs)               75
# 0x09, 0x02,                    //  Usage (Vendor Usage 0x02)          77
# 0x91, 0x00,                    //  Output (Data,Arr,Abs)              79
# 0xc0,                          // End Collection                      81
# 0x06, 0x00, 0xff,              // Usage Page (Vendor Defined Page 1)  82
# 0x09, 0x01,                    // Usage (Vendor Usage 1)              85
# 0xa1, 0x01,                    // Collection (Application)            87
# 0x09, 0x0a,                    //  Usage (Vendor Usage 0x0a)          89
# 0xa1, 0x02,                    //  Collection (Logical)               91
# 0x85, 0xff,                    //   Report ID (255)                   93
# 0x95, 0x01,                    //   Report Count (1)                  95
# 0x75, 0x20,                    //   Report Size (32)                  97
# 0x09, 0x0b,                    //   Usage (Vendor Usage 0x0b)         99
# 0x17, 0x01, 0x00, 0x00, 0x80,  //   Logical Minimum (-2147483647)     101
# 0x27, 0xff, 0xff, 0xff, 0x7f,  //   Logical Maximum (2147483647)      106
# 0x81, 0x02,                    //   Input (Data,Var,Abs)              111
# 0xc0,                          //  End Collection                     113
# 0x09, 0x22,                    //  Usage (Vendor Usage 0x22)          114
# 0xa1, 0x02,                    //  Collection (Logical)               116
# 0x85, 0x90,                    //   Report ID (144)                   118
# 0x09, 0x33,                    //   Usage (Vendor Usage 0x33)         120
# 0x75, 0x08,                    //   Report Size (8)                   122
# 0x15, 0x00,                    //   Logical Minimum (0)               124
# 0x26, 0xff, 0x00,              //   Logical Maximum (255)             126
# 0x81, 0x02,                    //   Input (Data,Var,Abs)              129
# 0x09, 0x34,                    //   Usage (Vendor Usage 0x34)         131
# 0x81, 0x02,                    //   Input (Data,Var,Abs)              133
# 0x05, 0x01,                    //   Usage Page (Generic Desktop)      135
# 0x09, 0x3b,                    //   Usage (Byte Count)                137
# 0x75, 0x10,                    //   Report Size (16)                  139
# 0x27, 0xff, 0xff, 0x00, 0x00,  //   Logical Maximum (65535)           141
# 0x81, 0x02,                    //   Input (Data,Var,Abs)              146
# 0x06, 0x00, 0xff,              //   Usage Page (Vendor Defined Page 1) 148
# 0x09, 0x0a,                    //   Usage (Vendor Usage 0x0a)         151
# 0xa1, 0x02,                    //   Collection (Logical)              153
# 0x05, 0x0a,                    //    Usage Page (Ordinals)            155
# 0x19, 0x01,                    //    Usage Minimum (1)                157
# 0x29, 0x0a,                    //    Usage Maximum (10)               159
# 0x95, 0x0a,                    //    Report Count (10)                161
# 0x75, 0x08,                    //    Report Size (8)                  163
# 0x26, 0xff, 0x00,              //    Logical Maximum (255)            165
# 0x81, 0x02,                    //    Input (Data,Var,Abs)             168
# 0xc0,                          //   End Collection                    170
# 0xc0,                          //  End Collection                     171
# 0x06, 0x00, 0xff,              //  Usage Page (Vendor Defined Page 1) 172
# 0x09, 0x22,                    //  Usage (Vendor Usage 0x22)          175
# 0xa1, 0x02,                    //  Collection (Logical)               177
# 0x85, 0x90,                    //   Report ID (144)                   179
# 0x09, 0x33,                    //   Usage (Vendor Usage 0x33)         181
# 0x95, 0x01,                    //   Report Count (1)                  183
# 0x91, 0x02,                    //   Output (Data,Var,Abs)             185
# 0x09, 0x34,                    //   Usage (Vendor Usage 0x34)         187
# 0x91, 0x02,                    //   Output (Data,Var,Abs)             189
# 0x05, 0x01,                    //   Usage Page (Generic Desktop)      191
# 0x09, 0x3b,                    //   Usage (Byte Count)                193
# 0x75, 0x10,                    //   Report Size (16)                  195
# 0x27, 0xff, 0xff, 0x00, 0x00,  //   Logical Maximum (65535)           197
# 0x91, 0x02,                    //   Output (Data,Var,Abs)             202
# 0x06, 0x00, 0xff,              //   Usage Page (Vendor Defined Page 1) 204
# 0x09, 0x0a,                    //   Usage (Vendor Usage 0x0a)         207
# 0xa1, 0x02,                    //   Collection (Logical)              209
# 0x05, 0x0a,                    //    Usage Page (Ordinals)            211
# 0x19, 0x01,                    //    Usage Minimum (1)                213
# 0x29, 0x0a,                    //    Usage Maximum (10)               215
# 0x95, 0x0a,                    //    Report Count (10)                217
# 0x75, 0x08,                    //    Report Size (8)                  219
# 0x26, 0xff, 0x00,              //    Logical Maximum (255)            221
# 0x91, 0x02,                    //    Output (Data,Var,Abs)            224
# 0xc0,                          //   End Collection                    226
# 0xc0,                          //  End Collection                     227
# 0x06, 0x00, 0xff,              //  Usage Page (Vendor Defined Page 1) 228
# 0x09, 0x22,                    //  Usage (Vendor Usage 0x22)          231
# 0xa1, 0x02,                    //  Collection (Logical)               233
# 0x85, 0xc4,                    //   Report ID (196)                   235
# 0x09, 0x33,                    //   Usage (Vendor Usage 0x33)         237
# 0x95, 0x01,                    //   Report Count (1)                  239
# 0x81, 0x02,                    //   Input (Data,Var,Abs)              241
# 0x09, 0x34,                    //   Usage (Vendor Usage 0x34)         243
# 0x81, 0x02,                    //   Input (Data,Var,Abs)              245
# 0x05, 0x01,                    //   Usage Page (Generic Desktop)      247
# 0x09, 0x3b,                    //   Usage (Byte Count)                249
# 0x75, 0x10,                    //   Report Size (16)                  251
# 0x27, 0xff, 0xff, 0x00, 0x00,  //   Logical Maximum (65535)           253
# 0x81, 0x02,                    //   Input (Data,Var,Abs)              258
# 0x06, 0x00, 0xff,              //   Usage Page (Vendor Defined Page 1) 260
# 0x09, 0x0a,                    //   Usage (Vendor Usage 0x0a)         263
# 0xa1, 0x02,                    //   Collection (Logical)              265
# 0x05, 0x0a,                    //    Usage Page (Ordinals)            267
# 0x19, 0x01,                    //    Usage Minimum (1)                269
# 0x29, 0x3b,                    //    Usage Maximum (59)               271
# 0x95, 0x3b,                    //    Report Count (59)                273
# 0x75, 0x08,                    //    Report Size (8)                  275
# 0x26, 0xff, 0x00,              //    Logical Maximum (255)            277
# 0x81, 0x02,                    //    Input (Data,Var,Abs)             280
# 0xc0,                          //   End Collection                    282
# 0xc0,                          //  End Collection                     283
# 0x06, 0x00, 0xff,              //  Usage Page (Vendor Defined Page 1) 284
# 0x09, 0x22,                    //  Usage (Vendor Usage 0x22)          287
# 0xa1, 0x02,                    //  Collection (Logical)               289
# 0x85, 0xc4,                    //   Report ID (196)                   291
# 0x09, 0x33,                    //   Usage (Vendor Usage 0x33)         293
# 0x95, 0x01,                    //   Report Count (1)                  295
# 0x91, 0x02,                    //   Output (Data,Var,Abs)             297
# 0x09, 0x34,                    //   Usage (Vendor Usage 0x34)         299
# 0x91, 0x02,                    //   Output (Data,Var,Abs)             301
# 0x05, 0x01,                    //   Usage Page (Generic Desktop)      303
# 0x09, 0x3b,                    //   Usage (Byte Count)                305
# 0x75, 0x10,                    //   Report Size (16)                  307
# 0x27, 0xff, 0xff, 0x00, 0x00,  //   Logical Maximum (65535)           309
# 0x91, 0x02,                    //   Output (Data,Var,Abs)             314
# 0x06, 0x00, 0xff,              //   Usage Page (Vendor Defined Page 1) 316
# 0x09, 0x0a,                    //   Usage (Vendor Usage 0x0a)         319
# 0xa1, 0x02,                    //   Collection (Logical)              321
# 0x05, 0x0a,                    //    Usage Page (Ordinals)            323
# 0x19, 0x01,                    //    Usage Minimum (1)                325
# 0x29, 0x3b,                    //    Usage Maximum (59)               327
# 0x95, 0x3b,                    //    Report Count (59)                329
# 0x75, 0x08,                    //    Report Size (8)                  331
# 0x26, 0xff, 0x00,              //    Logical Maximum (255)            333
# 0x91, 0x02,                    //    Output (Data,Var,Abs)            336
# 0xc0,                          //   End Collection                    338
# 0xc0,                          //  End Collection                     339
# 0x06, 0x00, 0xff,              //  Usage Page (Vendor Defined Page 1) 340
# 0x09, 0x0c,                    //  Usage (Vendor Usage 0x0c)          343
# 0xa1, 0x02,                    //  Collection (Logical)               345
# 0x85, 0xff,                    //   Report ID (255)                   347
# 0x05, 0x01,                    //   Usage Page (Generic Desktop)      349
# 0x09, 0x3b,                    //   Usage (Byte Count)                351
# 0x95, 0x01,                    //   Report Count (1)                  353
# 0xb1, 0x02,                    //   Feature (Data,Var,Abs)            355
# 0x09, 0x3a,                    //   Usage (Counted Buffer)            357
# 0xa1, 0x02,                    //   Collection (Logical)              359
# 0x05, 0x0a,                    //    Usage Page (Ordinals)            361
# 0x19, 0x01,                    //    Usage Minimum (1)                363
# 0x29, 0x3e,                    //    Usage Maximum (62)               365
# 0x95, 0x3e,                    //    Report Count (62)                367
# 0xb1, 0x02,                    //    Feature (Data,Var,Abs)           369
# 0xc0,                          //   End Collection                    371
# 0xc0,                          //  End Collection                     372
# 0x06, 0x00, 0xff,              //  Usage Page (Vendor Defined Page 1) 373
# 0x09, 0x0c,                    //  Usage (Vendor Usage 0x0c)          376
# 0xa1, 0x02,                    //  Collection (Logical)               378
# 0x85, 0xe2,                    //   Report ID (226)                   380
# 0x05, 0x01,                    //   Usage Page (Generic Desktop)      382
# 0x09, 0x3b,                    //   Usage (Byte Count)                384
# 0x95, 0x01,                    //   Report Count (1)                  386
# 0x81, 0x02,                    //   Input (Data,Var,Abs)              388
# 0x09, 0x3a,                    //   Usage (Counted Buffer)            390
# 0xa1, 0x02,                    //   Collection (Logical)              392
# 0x05, 0x0a,                    //    Usage Page (Ordinals)            394
# 0x19, 0x01,                    //    Usage Minimum (1)                396
# 0x29, 0x3e,                    //    Usage Maximum (62)               398
# 0x95, 0x3e,                    //    Report Count (62)                400
# 0x81, 0x02,                    //    Input (Data,Var,Abs)             402
# 0xc0,                          //   End Collection                    404
# 0xc0,                          //  End Collection                     405
# 0xc0,                          // End Collection                      406
#
R: 407 05 0c 09 01 a1 01 85 01 09 e9 09 ea 75 01 95 02 15 00 25 01 81 02 75 06 95 01 81 03 75 18 81 03 c0 05 0b 09 01 a1 01 85 08 09 2f 75 01 81 06 09 20 81 06 75 06 81 03 c0 06 43 ff 0a 02 02 a1 01 85 11 95 13 75 08 26 ff 00 09 02 81 00 09 02 91 00 c0 06 00 ff 09 01 a1 01 09 0a a1 02 85 ff 95 01 75 20 09 0b 17 01 00 00 80 27 ff ff ff 7f 81 02 c0 09 22 a1 02 85 90 09 33 75 08 15 00 26 ff 00 81 02 09 34 81 02 05 01 09 3b 75 10 27 ff ff 00 00 81 02 06 00 ff 09 0a a1 02 05 0a 19 01 29 0a 95 0a 75 08 26 ff 00 81 02 c0 c0 06 00 ff 09 22 a1 02 85 90 09 33 95 01 91 02 09 34 91 02 05 01 09 3b 75 10 27 ff ff 00 00 91 02 06 00 ff 09 0a a1 02 05 0a 19 01 29 0a 95 0a 75 08 26 ff 00 91 02 c0 c0 06 00 ff 09 22 a1 02 85 c4 09 33 95 01 81 02 09 34 81 02 05 01 09 3b 75 10 27 ff ff 00 00 81 02 06 00 ff 09 0a a1 02 05 0a 19 01 29 3b 95 3b 75 08 26 ff 00 81 02 c0 c0 06 00 ff 09 22 a1 02 85 c4 09 33 95 01 91 02 09 34 91 02 05 01 09 3b 75 10 27 ff ff 00 00 91 02 06 00 ff 09 0a a1 02 05 0a 19 01 29 3b 95 3b 75 08 26 ff 00 91 02 c0 c0 06 00 ff 09 0c a1 02 85 ff 05 01 09 3b 95 01 b1 02 09 3a a1 02 05 0a 19 01 29 3e 95 3e b1 02 c0 c0 06 00 ff 09 0c a1 02 85 e2 05 01 09 3b 95 01 81 02 09 3a a1 02 05 0a 19 01 29 3e 95 3e 81 02 c0 c0 c0
N: Logitech G733 Gaming Headset
I: 3 046d 0ab5
```

### CODE REVIEW

**Comment by amfern** [comment]
@FFY00 would it be ok to merge it for the sake LED that are working open a different issue for buttons?

**Comment by FFY00** [comment]
Hum, we could add an option to overwrite the button count and then merge this with the button count set to 0 so that they don't show up. I think that is better than having broken buttons, and allow the driver to even atempt to interact with that configuration. You can base that on #969.

**Comment by FFY00** [comment]
Hi, I know this is a bit annoying, but would you mind reverting the merge commit and rebasing on master instead?

Depending on your local setup, it should be something like
```
$ git reset --hard HEAD~1
$ git fetch origin   # to make sure we are up to data
$ git rebase origin/master
```
(the `origin` remote here is `https://github.com/libratbag/libratbag.git`)

**Comment by mtayllan** [comment]
I've made the rebase

**Review by perigoso — APPROVED** [review]
LGTM

**Comment by amfern** [comment]
LGTM

**Pull request merged**
