### PR TITLE
Add support for the Logitech G915

### PR DESCRIPTION
**Pull request by FFY00**
Needs #874

### CODE REVIEW

**Comment by stephanlachnit** [comment]
Is it really a good idea to keep all device file in one directory, especially if we don't have a `DeviceType` property?

**Comment by FFY00** [comment]
Yes? Each device file contains the driver name (`Driver=hidpp20`) and all the required configurations to work properly with that driver. I am not sure I follow.

**Comment by stephanlachnit** [comment]
> Yes? Each device file contains the driver name (`Driver=hidpp20`) and all the required configurations to work properly with that driver. I am not sure I follow.

I think I was more thinking about piper, because here the UI handling would be different but it's not directly related to libratbag.

**Comment by FFY00** [comment]
> I think I was more thinking about piper, because here the UI handling would be different but it's not directly related to libratbag.

Well, kind of. The SVGs are bigger, we would need to adapt piper for that. But right now it works fine with the default (fallback) SVG.

**Comment by FFY00** [comment]
At least for me, the main thing is the ability to configure the leds, and that is working just fine. Button remapping is not great, but it was not great for mice either way.

**Comment by whot** [comment]
ftr, piper only needs the files for "this device needs that SVG". whereas the libratbag files are "here  are the custom quirks for this device", including things like the driver name.  both files are internal API, so If we ever need a device type property, we can add it then.

**Pull request merged**
