### PR TITLE
data: add device file and svg for Logitech G603

### PR DESCRIPTION
**Pull request by damex**
wireless receiver is the same as on g403 and g900.

bluetooth seem to be occasionally working with my dw1820a wifi+bluetooth(4.1) adapter and detected as g603.

tested on ubuntu 18.04.1.

does not work over bluetooth with my intel 9260 wifi+bluetooth(5.0) returning error:

`ratbag error: G603: error opening hidraw node (Connection timed out)`

works perfectly over usb wireless adapter.

just configuration files. should be safe to merge.

```
[G603]# info
Device F5:51:9C:7A:17:8E (random)
	Name: G603
	Alias: G603
	Appearance: 0x03c2
	Icon: input-mouse
	Paired: yes
	Trusted: yes
	Blocked: no
	Connected: yes
	LegacyPairing: no
	UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
	UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
	UUID: Device Information        (0000180a-0000-1000-8000-00805f9b34fb)
	UUID: Battery Service           (0000180f-0000-1000-8000-00805f9b34fb)
	UUID: Human Interface Device    (00001812-0000-1000-8000-00805f9b34fb)
	UUID: Vendor specific           (00010000-0000-1000-8000-011f2000046d)
	Modalias: usb:v046DpB01Cd0028
```

```
event18:   G603
```
```
event18 - G603
               SVG: /usr/share/libratbag/gnome/logitech-g603.svg
      Capabilities: query-configuration, resolution, switchable-resolution, profile, disable-profile, button, button-keys, led
 Number of Buttons: 6
    Number of Leds: 2
Number of Profiles: 1
Profile 0: (active)
  Name : 'Profile 1'
  Resolutions:
    0: 400dpi @ 1000Hz
    1: 800dpi @ 1000Hz (active) (default)
    2: 1600dpi @ 1000Hz
    3: 3200dpi @ 1000Hz
    4: <disabled>
  Button: 0 type unknown is mapped to 'button 1'
  Button: 1 type unknown is mapped to 'button 2'
  Button: 2 type unknown is mapped to 'button 3'
  Button: 3 type unknown is mapped to 'button 4'
  Button: 4 type unknown is mapped to 'button 5'
  Button: 5 type unknown is mapped to 'resolution-cycle-up'
  LED: 0 type: logo, depth: rgb, mode: off
  LED: 1 type: side, depth: rgb, mode: off
```
```
event19:   Logitech USB Receiver
```
```
event19 - Logitech USB Receiver
               SVG: /usr/share/libratbag/gnome/logitech-g900.svg
      Capabilities: query-configuration, resolution, switchable-resolution, profile, disable-profile, button, button-keys, led
 Number of Buttons: 6
    Number of Leds: 2
Number of Profiles: 1
Profile 0: (active)
  Name : 'Profile 1'
  Resolutions:
    0: 400dpi @ 1000Hz
    1: 800dpi @ 1000Hz (active) (default)
    2: 1600dpi @ 1000Hz
    3: 3200dpi @ 1000Hz
    4: <disabled>
  Button: 0 type unknown is mapped to 'button 1'
  Button: 1 type unknown is mapped to 'button 2'
  Button: 2 type unknown is mapped to 'button 3'
  Button: 3 type unknown is mapped to 'button 4'
  Button: 4 type unknown is mapped to 'button 5'
  Button: 5 type unknown is mapped to 'resolution-cycle-up'
  LED: 0 type: logo, depth: rgb, mode: off
  LED: 1 type: side, depth: rgb, mode: off
```

### CODE REVIEW

**Comment by phomes** [comment]
Seems mostly okay, but does it have two individual LEDs? The 403 has a LED in the center of the scroll wheel. As far as I can see that is not the case for the 603. So it should probably have its own .svg file (you can try to edit a copy of the 403 with inkscape).

I have no experience with the hidpp20 mice, so it is probably better for one of the others to check if the output is reasonable, and if the error with bluetooth is acceptable.

**Comment by damex** [comment]
> but does it have two individual LEDs?
it does not have any leds at'all.

> it should probably have its own .svg file (you can try to edit a copy of the 403 with inkscape).
i see that people used to make a symlink before. is that a wrong way now?

**Comment by Hjdskes** [comment]
If the device is actually different (i.e., it has no LEDs where the G403 has two), then yes, a symlink is wrong. It shouldn't be that hard to open the G403 svg in Inkscape and remove the LEDs.

**Comment by Hjdskes** [comment]
When the SVG file is merged from #600, this can go in as well.

**Comment by Hjdskes** [comment]
With #600 merged, we can just cherry pick the device file from this PR and merge it.

**Pull request closed without merging**
