### PR TITLE
drivers: add Roccat Kone Pure driver

### PR DESCRIPTION
**Pull request by stephanlachnit**
What I basically did was taking #682, copying the device specific changes and putting it in an own driver, as it was suggested in that PR. However first of all I don't even have that mouse so I really can't test it and secondly I don't think it's a very nice solution since 90% of the code is duplicated.
But if someone can test it and everything works, I thinks it better to have this than having nothing. If someone has the mouse and wants to add features, @hipnoizz provided some informations in his [wiki](https://github.com/hipnoizz/libratbag/wiki/Roccat-Kone-Pure), but sadly it looks like he is not actively developing the support anymore.

### CODE REVIEW

**Comment by FFY00** [comment]
I just want to revisit the discussion. @bentiss are you sure this is worth having its own driver?

This is the diff between `driver-roccat.c` and `driver-roccar-kone-pure.c`:
```diff
37c37
< #define ROCCAT_BUTTON_MAX			23
---
> #define ROCCAT_BUTTON_MAX			17
49,50c49,50
< #define ROCCAT_REPORT_SIZE_PROFILE		77
< #define ROCCAT_REPORT_SIZE_SETTINGS		43
---
> #define ROCCAT_REPORT_SIZE_PROFILE		59
> #define ROCCAT_REPORT_SIZE_SETTINGS		31
71,72c71,72
< 	uint8_t padding2[21];
< 	uint16_t checksum;
---
> 	uint8_t padding2[11];
> //	uint16_t checksum;
115,133c115,127
< 	{ 5, RATBAG_BUTTON_TYPE_WHEEL_LEFT },
< 	{ 6, RATBAG_BUTTON_TYPE_WHEEL_RIGHT },
< 	{ 7, RATBAG_BUTTON_TYPE_WHEEL_UP },
< 	{ 8, RATBAG_BUTTON_TYPE_WHEEL_DOWN },
< 	{ 9, RATBAG_BUTTON_TYPE_RESOLUTION_UP },
< 	{ 10, RATBAG_BUTTON_TYPE_RESOLUTION_DOWN },
< //	{ 11, RATBAG_BUTTON_TYPE_ }, /* top button above the wheel */
< 	{ 12, RATBAG_BUTTON_TYPE_LEFT },
< 	{ 13, RATBAG_BUTTON_TYPE_RIGHT },
< 	{ 14, RATBAG_BUTTON_TYPE_MIDDLE },
< 	{ 15, RATBAG_BUTTON_TYPE_EXTRA },
< 	{ 16, RATBAG_BUTTON_TYPE_SIDE },
< 	{ 17, RATBAG_BUTTON_TYPE_WHEEL_LEFT },
< 	{ 18, RATBAG_BUTTON_TYPE_WHEEL_RIGHT },
< 	{ 19, RATBAG_BUTTON_TYPE_WHEEL_UP },
< 	{ 20, RATBAG_BUTTON_TYPE_WHEEL_DOWN },
< 	{ 21, RATBAG_BUTTON_TYPE_RESOLUTION_UP },
< 	{ 22, RATBAG_BUTTON_TYPE_RESOLUTION_DOWN },
< //	{ 23, RATBAG_BUTTON_TYPE_ }, /* top button above the wheel */
---
> 	{ 5, RATBAG_BUTTON_TYPE_WHEEL_UP },
> 	{ 6, RATBAG_BUTTON_TYPE_WHEEL_DOWN },
> 	{ 7, RATBAG_BUTTON_TYPE_RESOLUTION_UP },
> 	{ 8, RATBAG_BUTTON_TYPE_RESOLUTION_DOWN },
> 	{ 9, RATBAG_BUTTON_TYPE_LEFT },
> 	{ 10, RATBAG_BUTTON_TYPE_RIGHT },
> 	{ 11, RATBAG_BUTTON_TYPE_MIDDLE },
> 	{ 12, RATBAG_BUTTON_TYPE_EXTRA },
> 	{ 13, RATBAG_BUTTON_TYPE_SIDE },
> 	{ 14, RATBAG_BUTTON_TYPE_WHEEL_UP },
> 	{ 15, RATBAG_BUTTON_TYPE_WHEEL_DOWN },
> 	{ 16, RATBAG_BUTTON_TYPE_RESOLUTION_UP },
> 	{ 17, RATBAG_BUTTON_TYPE_RESOLUTION_DOWN },
164,165c158,159
< 	{ 9, BUTTON_ACTION_SPECIAL(RATBAG_BUTTON_ACTION_SPECIAL_WHEEL_LEFT) },
< 	{ 10, BUTTON_ACTION_SPECIAL(RATBAG_BUTTON_ACTION_SPECIAL_WHEEL_RIGHT) },
---
> 	//{ 9, BUTTON_ACTION_SPECIAL(RATBAG_BUTTON_ACTION_SPECIAL_WHEEL_LEFT) },
> 	//{ 10, BUTTON_ACTION_SPECIAL(RATBAG_BUTTON_ACTION_SPECIAL_WHEEL_RIGHT) },
177c171
< 	{ 32, BUTTON_ACTION_KEY(KEY_CONFIG) },
---
> 	//{ 32, BUTTON_ACTION_KEY(KEY_CONFIG) },
658c652
< 	if (dpi_x < 200 || dpi_x > 8200 || dpi_x % 50)
---
> 	if (dpi_x < 100 || dpi_x > 5000 || dpi_x % 50)
660c654
< 	if (dpi_y < 200 || dpi_y > 8200 || dpi_y % 50)
---
> 	if (dpi_y < 100 || dpi_y > 5000 || dpi_y % 50)
666a661,662
> 	if (resolution->is_active)
> 		settings_report->current_dpi = resolution->index;
670c666,667
< 	settings_report->checksum = roccat_compute_crc(buf, ROCCAT_REPORT_SIZE_SETTINGS);
---
> 	// No checksum for settings report on Kone Pure.
> 	//settings_report->checksum = roccat_compute_crc(buf, ROCCAT_REPORT_SIZE_SETTINGS);
745c742
< 		ratbag_resolution_set_dpi_list_from_range(resolution, 200, 8200);
---
> 		ratbag_resolution_set_dpi_list_from_range(resolution, 100, 5000);
748,750d744
< 	ratbag_profile_for_each_button(profile, button)
< 		roccat_read_button(button);
<
760a755,758
> 	// Buttons were read from the buffer that was yet un-initialized with the device data.
> 	ratbag_profile_for_each_button(profile, button)
> 		roccat_read_button(button);
>
839c837
< 	.name = "Roccat Kone XTD",
---
> 	.name = "Roccat Kone Pure",
```

As I don't have any Roccat device, merging the drivers would only make sense if @stephanlachnit is open to doing it.

From a structural POV I think it would make sense to merge the drivers, but we live in the real world and that would mean more work :confused:.

**Comment by whot** [comment]
whoah, a non-unified diff. there's a blast from the past :) I recommend `alias diff='diff -u'` in your shell config because no-one uses non-unified diffs anymore but diff itself will never change the default.

could be that the drivers can be merged, mostly depends on @stephanlachnit and whether he wants to do that effort. However - given that even he doesn't have that device and we haven't really seen a lot of feedback here I think it's safer to just leave them separate - that way a change in one doesn't inadvertently break the other one without us ever being able to test them.

**Comment by FFY00** [comment]
> whoah, a non-unified diff. there's a blast from the past :) I recommend alias diff='diff -u' in your shell config because no-one uses non-unified diffs anymore but diff itself will never change the default.

Thanks :)

> could be that the drivers can be merged, mostly depends on @stephanlachnit and whether he wants to do that effort. However - given that even he doesn't have that device and we haven't really seen a lot of feedback here I think it's safer to just leave them separate - that way a change in one doesn't inadvertently break the other one without us ever being able to test them.

Sure, once we have a proper CI we can merge them without having the actual devices :grin:

**Comment by stephanlachnit** [comment]
I don't plan to merge the drivers, at least not in any near future. The effort isn't really appealing to me and without at least one of the devices it doesn't make a lot sense anyway. I was mainly looking through Issues/PRs on piper which can be fixed easily and somehow landed here :D

**Pull request merged**
