### PR TITLE
gitignore: add builddir

### PR DESCRIPTION
**Pull request by stephanlachnit**
`builddir` should be ignored and the old gitignore from ratbagd can be deleted.

### CODE REVIEW

**Comment by FFY00** [comment]
Duplicate of #672 

TLDR: That should be in your personal .gitignore

**Comment by FFY00** [comment]
Ah, sorry. Missed you removing the old .gitignore, can you leave just that?

**Comment by stephanlachnit** [comment]
> Duplicate of #672
> 
> TLDR: That should be in your personal .gitignore

Must be the wrong link, the 672 has nothing to do with a gitignore^^
But why should it be in the personal one? The readme explicitly recommends the build dir `builddir`, so everything in there should be ignored from git.

**Comment by FFY00** [comment]
Yes, sorry. Should be #671.

**Comment by stephanlachnit** [comment]
> Yes, sorry. Should be #671.

A thx. But then the complete gitignore should be removed, so you can simply add `.gitignore` to your gitignore without conflicts. Will update the PR.

**Comment by FFY00** [comment]
No, you add it to `~/.gitignore` :grin:.

**Comment by FFY00** [comment]
Sorry, we should only remove `ratbagd/.gitignore`, not `.gitignore`.

**Comment by stephanlachnit** [comment]
> Sorry, we should only remove `ratbagd/.gitignore`, not `.gitignore`.

No both, @bentiss and @whot even mentioned this in #671. Everything that will be changed will be contained in the your build directory, which you should add to your personal `.gitignore`.

**Comment by FFY00** [comment]
Ah, sorry. My bad.

**Pull request merged**
