### PR TITLE
steelseries: fix regression in v2 led

### LINKED ISSUE #683: rival 310: led setting changes are not applied to mouse
can't change any led settings in a Rival 310 

initial settings
```
 ratbagctl warbling-mara profile 0 get
Profile 0: (active)
Name: n/a
Report Rate: 1000Hz
Resolutions:
  0: 800dpi (default)
  1: 1600dpi (active)
Button: 0 is mapped to 'button 1'
Button: 1 is mapped to 'button 2'
Button: 2 is mapped to 'button 3'
Button: 3 is mapped to 'button 4'
Button: 4 is mapped to 'button 5'
Button: 5 is mapped to 'resolution-cycle-up'
LED: 0, depth: rgb, mode: on, color: 000000
LED: 1, depth: rgb, mode: on, color: 000000
```

if I try 

```
ratbagctl warbling-mara led 0 set color  0000ff
```
the color in the profile changes but not in the mouse

```
...
LED: 0, depth: rgb, mode: on, color: 0000ff
...
```

in ratbagcltd log I get

```
ratbag debug: Profile 0 changed, rewriting
```

dbus gives an error
```
dbus-daemon[554]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.29422" (uid=0 pid=14054 comm="ratbagd --verbose ") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.UnknownMethod" requested_reply="0" destination=":1.29511" (uid=1000 pid=16247 comm="python3 /usr/bin/ratbagctl warbling-mara led 0 set")
```

using piper I get 
> Something gone wrong. The device has been reset to a previous state.

Info when connecting mouse
```
ratbag debug: New device: SteelSeries SteelSeries Rival 310 eSports Mouse
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver steelseries
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1720
ratbag debug: SteelSeries SteelSeries Rival 310 eSports Mouse is device '/dev/hidraw0'.
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1720
ratbag debug: SteelSeries SteelSeries Rival 310 eSports Mouse is device '/dev/hidraw1'.
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1720
ratbag debug: SteelSeries SteelSeries Rival 310 eSports Mouse is device '/dev/hidraw2'.
ratbag debug: HID report ID 01
ratbag debug: HID report ID 02
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1720
ratbag debug: SteelSeries SteelSeries Rival 310 eSports Mouse is device '/dev/hidraw0'.
ratbag debug: HID report ID 01
ratbag debug: HID report ID 02
ratbag debug: HID report ID 01
ratbag debug: HID report ID 02
ratbag debug: SteelSeries firmware version 1.33
ratbag debug: driver match found: SteelSeries
hidraw0: "SteelSeries SteelSeries Rival 310 eSports Mouse", 1 profiles
ratbag debug: New device: SteelSeries SteelSeries Rival 310 eSports Mouse
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver steelseries
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1720
ratbag debug: SteelSeries SteelSeries Rival 310 eSports Mouse is device '/dev/hidraw0'.
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1720
ratbag debug: SteelSeries SteelSeries Rival 310 eSports Mouse is device '/dev/hidraw1'.
ratbag debug: New device: SteelSeries SteelSeries Rival 310 eSports Mouse
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver steelseries
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1720
ratbag debug: SteelSeries SteelSeries Rival 310 eSports Mouse is device '/dev/hidraw0'.
ratbag debug: hidraw info: bus 0x03 vendor 0x1038 product 0x1720
ratbag debug: SteelSeries SteelSeries Rival 310 eSports Mouse is device '/dev/hidraw1'.
```

ratbag version 0.9.905 running in Arch Linux

### PR DESCRIPTION
**Pull request by FFY00**
Fixes #683

@danielfpferreira can you confirm this solves your issue?

### CODE REVIEW

**Comment by whot** [comment]
got a bit confused at first, for next time please separate out whitespace fixes. Much easier to get to the gist of a patch that actually changes things. But otherwise, LGTM, thanks.

**Comment by FFY00** [comment]
I didn't really notice, the editor I was using removed them automatically.

**Comment by whot** [comment]
General advice: always use `git add -p`, never use `git add -a`. Feels annoying at first, but it does force you to re-review every bit you add to a commit and long-term makes life a lot easier - you can fix small things while working on longer patches and get them committed on the fly.

**Comment by FFY00** [comment]
Hum... I never used `-p`. I usually just `git add` and `git push`. Thanks for the suggestion.

**Comment by danielfpferreira** [comment]
@FFY00 just tested it works fine thank you

**Comment by whot** [comment]
force yourself to use `git add -p` for a few weeks exclusively. You probably won't go back to plain `git add` anymore*. Also, the sort-of counterpart to `git add -p` is `git checkout -p` where you can remove changes hunk-by-hunk from the tree. Play with it.


* and at some point you'll get proficient at editing diffs directly which is also incredibly useful.

**Comment by FFY00** [comment]
I don't think I have a problem with that, I just never needed to explicitly use this function so I din't even know it was there :laughing:.

**Pull request merged**
