### PR TITLE
Add: Roccat Kone Pro

### PR DESCRIPTION
**Pull request by vibrantleaf**

### CODE REVIEW

**Review by staticssleever668 — CHANGES_REQUESTED** [review]
Hi!
```
LedType=RGB
Leds=2
DpiRange=50:8000@10
Profiles=5
Buttons=8
```
This part has no effect, as it's placed in incorrect place and libratbag's roccat driver doesn't support such options anyway.
Does this work fine? Could you post the output of verbose ratbagd? `sudo systemctl stop ratbagd && sudo ratbagd --verbose=raw`.

**Comment by vibrantleaf** [comment]
Hello,
sorry for adding those unneeded values.
it seems to be working fine (i think)

sure heres the output
```
Initializing libratbag
ratbag debug: New device: AsusTek Computer Inc. AURA LED Controller
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 0b05:19af
ratbag debug: New device: USBMIC1
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 0c76:1618
ratbag debug: New device: ROCCAT ROCCAT Kone Pro
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver roccat
ratbag debug: hidraw info: bus 0x03 vendor 0x1e7d product 0x2c88
ratbag debug: ROCCAT ROCCAT Kone Pro is device '/dev/hidraw5'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: New device: ROCCAT ROCCAT Kone Pro
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver roccat
ratbag debug: hidraw info: bus 0x03 vendor 0x1e7d product 0x2c88
ratbag debug: ROCCAT ROCCAT Kone Pro is device '/dev/hidraw6'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: New device: ROCCAT ROCCAT Kone Pro
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver roccat
ratbag debug: hidraw info: bus 0x03 vendor 0x1e7d product 0x2c88
ratbag debug: ROCCAT ROCCAT Kone Pro is device '/dev/hidraw7'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 01
ratbag debug: - HID report ID 02
ratbag debug: - HID report ID 06
ratbag debug: - HID report ID 04
ratbag debug: - HID report ID 03
ratbag debug: - HID report ID 05
ratbag debug: New device: ROCCAT ROCCAT Kone Pro
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: device assigned driver roccat
ratbag debug: hidraw info: bus 0x03 vendor 0x1e7d product 0x2c88
ratbag debug: ROCCAT ROCCAT Kone Pro is device '/dev/hidraw8'.
ratbag debug: Parsing HID report descriptor
ratbag debug: Parsing HID report descriptor
ratbag debug: - HID report ID 04
ratbag debug: - HID report ID 05
ratbag debug: - HID report ID 06
ratbag debug: - HID report ID 07
ratbag debug: - HID report ID 08
ratbag debug: - HID report ID 09
ratbag debug: - HID report ID 0a
ratbag debug: - HID report ID 0d
ratbag debug: - HID report ID 0e
ratbag debug: - HID report ID 0f
ratbag debug: - HID report ID 10
ratbag debug: - HID report ID 11
ratbag debug: - HID report ID 12
ratbag debug: - HID report ID 13
ratbag raw: feature set:   04 00 80
ratbag raw: feature get:   04 01 00
ratbag raw: feature get:   06 45 00 06 06 03 01 3c 00 3c 00 18 00 20 00 40 00 08 00 10 00 18 00 20 00 40 00 00 00 03 09 06 ff 0f 00 00 14 ff 00 48 ff 14 ff
ratbag error: error while reading the report rate of the mouse (0x00)
ratbag raw: feature set:   04 00 90
ratbag raw: feature get:   04 01 00
ratbag raw: feature get:   07 45 00 00 00 01 01 00 00 02 01 00 01 03 01 00 00 09 01 00 00 0a 01 00 0e 05 01 00 00 06 01 00 00 01 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 8f 00 00 00 00 00 00 00 00 00
ratbag raw: checksum computed: 0x011e, checksum given: 0x0000
ratbag error: Error while reading profile 0, continuing...
ratbag raw: profile: 0 ../src/driver-roccat.c:768
ratbag raw: feature set:   04 01 80
ratbag raw: feature get:   04 01 00
ratbag raw: feature get:   06 45 01 06 06 03 01 32 00 32 00 18 00 20 00 40 00 08 00 10 00 18 00 20 00 40 00 00 00 00 0a 06 ff 0f 00 00 14 ff 00 48 ff 14 ff
ratbag error: error while reading the report rate of the mouse (0x00)
ratbag raw: feature set:   04 01 90
ratbag raw: feature get:   04 01 00
ratbag raw: feature get:   07 45 01 00 00 01 01 00 00 02 01 00 00 03 01 00 00 09 01 00 00 0a 01 00 00 05 01 00 00 06 01 00 00 01 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 81 00 00 00 00 00 00 00 00 00
ratbag raw: checksum computed: 0x0102, checksum given: 0x0000
ratbag error: Error while reading profile 1, continuing...
ratbag raw: profile: 1 ../src/driver-roccat.c:768
ratbag raw: feature set:   04 02 80
ratbag raw: feature get:   04 01 00
ratbag raw: feature get:   06 45 02 00 00 1f 01 08 00 10 00 18 00 20 00 40 00 00 00 00 00 00 00 00 00 00 00 00 00 03 03 06 ff 0f 00 00 ff ff 00 00 ff ff ff
ratbag raw: feature set:   04 02 90
ratbag raw: feature get:   04 01 00
ratbag raw: feature get:   07 45 02 00 00 01 01 00 00 02 01 00 00 03 01 00 00 09 01 00 00 0a 01 00 00 05 01 00 00 06 01 00 00 01 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 82 00 00 00 00 00 00 00 00 00
ratbag raw: checksum computed: 0x0104, checksum given: 0x0000
ratbag error: Error while reading profile 2, continuing...
ratbag raw: profile: 2 ../src/driver-roccat.c:768
ratbag raw: feature set:   04 03 80
ratbag raw: feature get:   04 01 00
ratbag raw: feature get:   06 45 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature set:   04 03 90
ratbag raw: feature get:   04 01 00
ratbag raw: feature get:   07 45 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 4f 00 00 00 00 00 00 00 00 00
ratbag raw: checksum computed: 0x009e, checksum given: 0x0000
ratbag error: Error while reading profile 3, continuing...
ratbag raw: profile: 3 ../src/driver-roccat.c:768
ratbag raw: feature set:   04 04 80
ratbag raw: feature get:   04 01 00
ratbag raw: feature get:   06 45 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
ratbag raw: feature set:   04 04 90
ratbag raw: feature get:   04 01 00
ratbag raw: feature get:   07 45 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 50 00 00 00 00 00 00 00 00 00
ratbag raw: checksum computed: 0x00a0, checksum given: 0x0000
ratbag error: Error while reading profile 4, continuing...
ratbag raw: profile: 4 ../src/driver-roccat.c:768
ratbag raw: feature get:   05 03 00
ratbag raw: 'ROCCAT ROCCAT Kone Pro' is in profile 0
ratbag debug: driver match found: Roccat Kone XTD
hidraw8: "ROCCAT ROCCAT Kone Pro", 5 profiles
ratbag debug: New device: Keychron Keychron V1
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 3434:0311
ratbag debug: New device: Keychron Keychron V1
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 3434:0311
ratbag debug: New device: Keychron Keychron V1
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 3434:0311
ratbag debug: New device: Yubico YubiKey FIDO
ratbag debug: Using data directory '/usr/share/libratbag'
ratbag debug: No data file found for 1050:0402
DBus server ready
```

**Comment by staticssleever668** [comment]
`ratbag error: error while reading the report rate of the mouse (0x00)`
then for all profiles it says:
`ratbag error: Error while reading profile 0, continuing...`.
Sorry, but I don't think I can merge it in this state :(

Still, did it allow you to change some mouse settings this way? Considering the errors, I would've hesitated to try it as there may have been a chance of soft-bricking.

**Comment by vibrantleaf** [comment]
thats understandable thank you for your time

**Pull request closed without merging**
