### PR TITLE
liblur improvements

### PR DESCRIPTION
**Pull request by whot**
Note: this changes the API for new_from_hidraw.

### CODE REVIEW

**Comment by bentiss** [comment]
Hey Peter,

patch "lur: add lur_device_get/set_userdata" is missing the liblur.sym additions.

**Comment by whot** [comment]
whoops, fixed. Branch updated to 379695fca236

**Comment by whot** [comment]
urgh, sorry, forgot I had something else on that branch. HEAD is f0602bd, this is the correct one now

**Comment by bentiss** [comment]
merged as of f233b6b.

I amended the commit "lur: add lur_device_get/set_userdata" to have the new symbols declared in LIBLUR_0.4.0.

**Pull request closed without merging**
