### PR TITLE
data: add device IDs for Logitech MX Anywhere 3

### PR DESCRIPTION
**Pull request by kepstin**
I've confirmed that the device shows up both when connected using unifying receiver and bluetooth.

### CODE REVIEW

**Review by FFY00 — APPROVED** [review]

**Comment by FFY00** [comment]
Thanks :)

**Comment by FFY00** [comment]
You are just missing adding the file in `meson.build`, after that we can merge.

**Comment by kepstin** [comment]
FYI, here's the output from ratbagctl info:
```
screaming-acouchy - Logitech MX Anywhere 3
             Model: usb:046d:4090:0
 Number of Buttons: 7
    Number of Leds: 0
Number of Profiles: 1
Profile 0: (active)
  Name: n/a
  Resolutions:
    0: 1000dpi (active)
  Button: 0 is mapped to 'button 1'
  Button: 1 is mapped to 'button 2'
  Button: 2 is mapped to 'button 3'
  Button: 3 is mapped to 'button 4'
  Button: 4 is mapped to 'button 5'
  Button: 5 is mapped to 'ratchet-mode-switch'
  Button: 6 is mapped to UNKNOWN
```
I'm not sure what Button 6 is here, all of the user controls are accounted for.
I'll take a look at the meson build file.

**Comment by FFY00** [comment]
The mouse reported to have 7 buttons, that's why 7 buttons show there. It is probably a firmware bug, it's common.

**Pull request merged**
