### PR TITLE
Add support for trigger mode

### PR DESCRIPTION
**Pull request by FFY00**

### CODE REVIEW

**Comment by phomes** [comment]
@whot @bentiss Do we want to support a Trigger mode for LEDs? The LED will light up for a set duration after clicking the configured button/key. I have not seen this feature on any device other than steelseries.

**Comment by bentiss** [comment]
I think the Logitech mice have some advanced trigger mechanism for the macros too, but IIRC, it's only linked to the button that initiates the macro. And now that I think about it, I do not think the macro could control the LEDs.

So my initial thought would be that we should hold off until more devices are supporting this, because we don't know if the API is the correct one based on only one device. For the record, we already removed features in the past because they were only for one particular device/brand, and maintaining too many features is something we do not want to be confronted with.

**Comment by FFY00** [comment]
@bentiss I totally understand. If it helps, I would be happy to maintain this feature.

**Comment by FFY00** [comment]
I am going to close this at it seems the changes won't be merged anytime soon.

**Pull request closed without merging**
