### PR TITLE
update and merge logitech g9x

### PR DESCRIPTION
**Pull request by heimer16**
Merged G9x with Call of Duty edition.
Updated with DPI LED
also updated min DPI (200) and increments (50), although I can't confirm if CoD edition is the same.
updated support links

### CODE REVIEW

**Comment by stephanlachnit** [comment]
@FFY00 can you include this in the new release? It's not much and looks good to me, I also checked that it works in Piper (see libratbag/piper#471).

**Comment by FFY00** [comment]
I don't understand why we need to do this. I don't see any reason to merge the two .device files.

**Comment by stephanlachnit** [comment]
> I don't understand why we need to do this. I don't see any reason to merge the two .device files.

If we want to change their properties, we don't want to do it twice (like in this PR, originally @heimer16 only changed it for the "original" version). It also happened in Piper, the "original" G9x was using the G9 svg but the CoD Edition not. As far as I can see it, the devices are identical except that one of them is painted and probably shows up with a different name in the Logitech software.

**Comment by stephanlachnit** [comment]
@jdz since you have the CoD edition of this mouse, can you somehow test if this PR reports the correct dpi? The website states the range (200-5700), but not the dpi step size.

**Comment by FFY00** [comment]
I still think we should keep the separated .device files.

**Comment by jdz** [comment]
Currently I get the following info about the mouse:

```
$ ratbagctl warbling-mara info
warbling-mara - Logitech G9x Laser Mouse
             Model: usb:046d:c249:0
 Number of Buttons: 13
    Number of Leds: 1
Number of Profiles: 5
Profile 0: (active)
  Name: Profile 1
  Report Rate: 1000Hz
  Resolutions:
    0: 3350x3350dpi
    1: 4450x4450dpi
    2: 5500x5500dpi
    3: <disabled>
    4: <disabled>
  Button: 0 is mapped to 'button 1'
  Button: 1 is mapped to 'button 2'
  Button: 2 is mapped to 'button 3'
  Button: 3 is mapped to 'button 4'
  Button: 4 is mapped to 'button 5'
  Button: 5 is mapped to UNKNOWN
  Button: 6 is mapped to 'wheel-left'
  Button: 7 is mapped to 'wheel-right'
  Button: 8 is mapped to 'resolution-up'
  Button: 9 is mapped to 'resolution-down'
  Button: 10 is mapped to UNKNOWN
  Button: 11 is mapped to UNKNOWN
  Button: 12 is mapped to UNKNOWN
  LED: 0, depth: rgb, mode: on, color: 0000ff
Profile 1: (disabled)
Profile 2: (disabled)
Profile 3: (disabled)
Profile 4: (disabled)
```

This is an old mouse, and I seem to remember that the max DPI was maybe around 8k or 9k, but I would not trust my memory on this.

But the reported info says current profile has only 3 resolutions enabled, but actually they are all set, and I can switch between them using the hardware buttons.

The color of the led seems to be reported correctly: it's blue.

I now manually edited the device file and updated max DPI to 9600, and get the following:

```
$ ratbagctl warbling-mara info                     
warbling-mara - Logitech G9x Laser Mouse
             Model: usb:046d:c249:0
 Number of Buttons: 13
    Number of Leds: 1
Number of Profiles: 5
Profile 0: (active)
  Name: Profile 1
  Report Rate: 1000Hz
  Resolutions:
    0: 3350x3350dpi
    1: 4450x4450dpi
    2: 5500x5500dpi (active)
    3: 7000x7000dpi (default)
    4: 8700x8700dpi
  Button: 0 is mapped to 'button 1'
  Button: 1 is mapped to 'button 2'
  Button: 2 is mapped to 'button 3'
  Button: 3 is mapped to 'button 4'
  Button: 4 is mapped to 'button 5'
  Button: 5 is mapped to UNKNOWN
  Button: 6 is mapped to 'wheel-left'
  Button: 7 is mapped to 'wheel-right'
  Button: 8 is mapped to 'resolution-up'
  Button: 9 is mapped to 'resolution-down'
  Button: 10 is mapped to UNKNOWN
  Button: 11 is mapped to UNKNOWN
  Button: 12 is mapped to UNKNOWN
  LED: 0, depth: rgb, mode: on, color: 0000ff
Profile 1: (disabled)
Profile 2: (disabled)
Profile 3: (disabled)
Profile 4: (disabled)
```

The chosen resolution is reported correctly (I can't be sure about the resolution, but it's the 3rd setting of 5), but if I change it using the hardwarde buttons, `ratbagctl info` still reports the old setting.  Only after restarting it is reporting the correct device state:

```
$ ratbagctl warbling-mara info  
warbling-mara - Logitech G9x Laser Mouse
             Model: usb:046d:c249:0
 Number of Buttons: 13
    Number of Leds: 1
Number of Profiles: 5
Profile 0: (active)
  Name: Profile 1
  Report Rate: 1000Hz
  Resolutions:
    0: 3350x3350dpi
    1: 4450x4450dpi
    2: 5500x5500dpi
    3: 7000x7000dpi (default)
    4: 8700x8700dpi (active)
  Button: 0 is mapped to 'button 1'
  Button: 1 is mapped to 'button 2'
  Button: 2 is mapped to 'button 3'
  Button: 3 is mapped to 'button 4'
  Button: 4 is mapped to 'button 5'
  Button: 5 is mapped to UNKNOWN
  Button: 6 is mapped to 'wheel-left'
  Button: 7 is mapped to 'wheel-right'
  Button: 8 is mapped to 'resolution-up'
  Button: 9 is mapped to 'resolution-down'
  Button: 10 is mapped to UNKNOWN
  Button: 11 is mapped to UNKNOWN
  Button: 12 is mapped to UNKNOWN
  LED: 0, depth: rgb, mode: on, color: 0000ff
Profile 1: (disabled)
Profile 2: (disabled)
Profile 3: (disabled)
Profile 4: (disabled)
```

**Comment by stephanlachnit** [comment]
> I still think we should keep the separated .device files.

Looking at @jdz's log it isn't even reported as a different mouse. If it actually is the same mouse (besides a different ID to show a different image in the Logitech software), I don't see why we shouldn't do it.
I already mentioned it, but the first version of this PR only changed it for the normal version. Changes like the LED and wrong min dpi probably would have gone missing for this model like it did with the USB-ID in Piper.

The questions are:
-Are they actually the same?
-What is the dpi range and step size?

> The chosen resolution is reported correctly (I can't be sure about the resolution, but it's the 3rd setting of 5)

Can you try to figure it out? For example by measuring the distance the mouse needs to go from one end of the screen to the other and diving screen width (pixels) by the distance (inches), or using something like https://www.mouse-sensitivity.com/dpianalyzer. I'm not entirely sure if that works correct though.
It would be imported to know because looking at your log from #959, it seems like this completely changes the reported resolution.

**Comment by jdz** [comment]
To go across the screen from left to right, 3840 pixels, in centimeters:

1. ~5.5
2. ~4.0 - 4.6
3. ~2.9 - 3.2
4. ~2.3
5. ~1.8

This gives us approxmately following PPI values, and factor of the reported resolution in the profile:

cm | PPI | profile resolution | factor
---|-----|--------------------|-------
5.5 | 1773.3818 | 3350 | 0.5293677
4.3 | 2268.2788 | 4450 | 0.5097256
3.0 | 3251.2 | 5500 | 0.5911273
2.3 | 4240.696 | 7000 | 0.6058137
1.8 | 5418.6665 | 8700 | 0.6228352

Even though I've set GNOME to use device default profile and default settings I have not rebooted after changing the settings.  But the factors seem fairly consistent for hand measuring.  On the other hand my measured 5418 is pretty close to 5700.

**Comment by stephanlachnit** [comment]
Thanks for measuring! The numbers look way closer to what you reported in #959, but still quite off. @whot is there an easy way to grab the reported dots from libinput or similar, so that mouse speed settings can't affecting it?

**Comment by FFY00** [comment]
https://github.com/libratbag/ratbag-emu/blob/5930050d8cb23cad09704ea14835b6cd3043f7e3/tests/base.py#L61

You can look at the python-libevdev documentation as a staring point: https://pkgbuild.com/~ffy00/documentation/python-libevdev/examples.html

**Comment by stephanlachnit** [comment]
Thanks! If I have too much time I might write a little python script to determine the dpi.

**Comment by heimer16** [comment]
I'm not 100% sure if the results here confirm it's the same or not, but there hasn't been movement on this in a while, so I've updated the PR to go back to just updating the g9x original for now because that's what I have and what I can confirm works  If we decide to merge the two device files later, let me know and I can, but I'd like to at least get the led merged in and working.

**Review by stephanlachnit — APPROVED** [review]
Alright, let's merge.

**Pull request merged**
