### PR TITLE
Register Roccat Kone Pure driver

### LINKED ISSUE #1006: ratbag error: Unknown driver roccat-kone-pure in roccat-kone-pure.device persists
#999 persists for me on both Ubuntu 18.04 and 20.04.
I installed the most recent packages from 
https://launchpad.net/~libratbag-piper/+archive/ubuntu/piper-libratbag-git
The roccat-kone-pure.device file was updated with the new USB signatures and I assume the repo reflects the most recent commits but the driver is still not found and thus results in

```
gregor@leia:~$ sudo service ratbagd status
● ratbagd.service - Daemon to introspect and modify configurable mice
   Loaded: loaded (/lib/systemd/system/ratbagd.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-06-10 10:18:12 CEST; 1min 8s ago
 Main PID: 15127 (ratbagd)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/ratbagd.service
           └─15127 /usr/bin/ratbagd

Jun 10 10:18:12 leia systemd[1]: Starting Daemon to introspect and modify configurable mice...
Jun 10 10:18:12 leia systemd[1]: Started Daemon to introspect and modify configurable mice.
Jun 10 10:18:12 leia ratbagd[15127]: ratbag error: Unknown driver roccat-kone-pure in roccat-kone-pure.device
Jun 10 10:18:12 leia ratbagd[15127]: ratbag error: Unknown driver roccat-kone-pure in roccat-kone-pure.device
```

### PR DESCRIPTION
**Pull request by stephanlachnit**
Closes #1006.

@Vectrex can you test this? Else it won't be merged.
If you need help to test it (i. e. how to use it without installing libratbag from source), just ask here, I'll help you.

### CODE REVIEW

**Comment by Vectrex** [comment]
Will give it a try.
If I can avoid compiling alltogether: Nice. Overwriting binaries and restarting services shouldn't be problem.
If I have to compile: Is there a simple way to list all the required dev dependencies?

**Comment by stephanlachnit** [comment]
You have to compile this code, no way around that. Here is the wiki entry: https://github.com/libratbag/libratbag/wiki/Building-from-source

But in short for you:
```sh
sudo apt install build-essential check git libevdev-dev libglib2.0-dev libjson-glib-dev libsystemd-dev libudev-dev libunistring-dev meson pkg-config python3-dev python3-evdev python3-gi python3-lxml swig
git clone https://github.com/libratbag/libratbag.git
cd libratbag
git checkout -b stephanlachnit/kone-pure master
git pull https://github.com/stephanlachnit/libratbag.git p/kone-pure
meson builddir -Dtests=false
meson compile -C builddir
```
This installs all build dependencies and compiles the code from this PR for you.
To test it, run:
```sh
cd builddir
sudo ./ratbagd.devel --verbose=debug # test if daemon shows an error, exit with ctrl+c
sudo ./ratbagctl.devel --verbose list # list devices, note name of your mouse
sudo ./ratbagctl.devel <device_name_here> info # show device info
```

**Comment by Vectrex** [comment]
Replacing
```
meson compile -C builddir
```
with
```
ninja -C builddir
```
gave me
```
gregor@leia:/tmp/libratbag$ ninja -C builddir
ninja: Entering directory `builddir'
[8/64] Compiling C object 'ratbag@sta/src_driver-hidpp10.c.o'.
../src/driver-hidpp10.c: In function ‘hidpp10drv_write_button’:
../src/driver-hidpp10.c:345:41: warning: passing argument 1 of ‘ratbag_action_keycode_from_macro’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   rc = ratbag_action_keycode_from_macro(action, &key, &modifiers);
                                         ^~~~~~
In file included from ../src/driver-hidpp10.c:48:0:
../src/libratbag-private.h:488:1: note: expected ‘struct ratbag_button_action *’ but argument is of type ‘const struct ratbag_button_action *’
 ratbag_action_keycode_from_macro(struct ratbag_button_action *action,
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[60/64] Generating 'hidpp@sha/hidpp.c'.
notype name breathing
notype name traveling
notype name blink
notype name on
/tmp/libratbag/src/hidpp20.h:227: Warning 503: Can't wrap class $unnamed5$ unless renamed to a valid identifier.
/tmp/libratbag/src/hidpp20.h:222: Warning 503: Can't wrap class $unnamed4$ unless renamed to a valid identifier.
/tmp/libratbag/src/hidpp20.h:218: Warning 503: Can't wrap class $unnamed3$ unless renamed to a valid identifier.
/tmp/libratbag/src/hidpp20.h:213: Warning 503: Can't wrap class $unnamed2$ unless renamed to a valid identifier.
[64/64] Linking target _hidpp.so.
```
Since the binaries are created anyway I gave it a try
```
gregor@leia:/tmp/libratbag/builddir$ sudo ./ratbagd.devel --verbose=debug
Installing DBus policy file to /etc/dbus-1/system.d/org.freedesktop.ratbag_devel1.conf
Initializing libratbag
Speicherzugriffsfehler
```

**Comment by stephanlachnit** [comment]
Hm, looks like you need to debug it to find out what's wrong, the error message is way to generic.

**Comment by Vectrex** [comment]
Can the warnings during compile time be ignored?

**Comment by Vectrex** [comment]
Anyway. Starting the non-devel version of ratbagd yields

```
gregor@leia:/tmp/libratbag/builddir$ sudo ./ratbagd
[sudo] Passwort für gregor: 
hidraw9: "ROCCAT ROCCAT Kone Pure", 5 profiles
```
from a second shell

```
gregor@leia:/tmp/libratbag/builddir$ sudo ./ratbagctl --verbose list
[sudo] Passwort für gregor: 
screaming-acouchy:   ROCCAT ROCCAT Kone Pure
```

```
gregor@leia:/tmp/libratbag/builddir$ sudo ./ratbagctl screaming-acouchy info
screaming-acouchy - ROCCAT ROCCAT Kone Pure
             Model: usb:1e7d:2dbe:0
 Number of Buttons: 18
    Number of Leds: 0
Number of Profiles: 5
Profile 0: (active)
  Name: n/a
  Report Rate: 1000Hz
  Resolutions:
    0: 800x800dpi
    1: 1600x1600dpi (active)
    2: 3200x3200dpi
    3: 6400x6400dpi
    4: 8200x8200dpi
  Button: 0 is mapped to 'button 1'
  Button: 1 is mapped to 'button 2'
  Button: 2 is mapped to 'button 3'
  Button: 3 is mapped to 'button 4'
  Button: 4 is mapped to 'button 5'
  Button: 5 is mapped to 'wheel-up'
  Button: 6 is mapped to 'wheel-down'
  Button: 7 is mapped to 'resolution-up'
  Button: 8 is mapped to 'resolution-down'
  Button: 9 is mapped to 'button 5'
  Button: 10 is mapped to 'button 4'
  Button: 11 is mapped to UNKNOWN
  Button: 12 is mapped to UNKNOWN
  Button: 13 is mapped to UNKNOWN
  Button: 14 is mapped to UNKNOWN
  Button: 15 is mapped to UNKNOWN
  Button: 16 is mapped to 'profile-up'
  Button: 17 is mapped to 'profile-down'
Profile 1:
  Name: n/a
  Report Rate: 1000Hz
  Resolutions:
    0: 800x800dpi (active)
    1: 1600x1600dpi
    2: 3200x3200dpi
    3: 6400x6400dpi
    4: 8200x8200dpi
  Button: 0 is mapped to 'button 1'
  Button: 1 is mapped to 'button 2'
  Button: 2 is mapped to 'button 3'
  Button: 3 is mapped to 'button 4'
  Button: 4 is mapped to 'second-mode'
  Button: 5 is mapped to 'wheel-up'
  Button: 6 is mapped to 'wheel-down'
  Button: 7 is mapped to 'resolution-up'
  Button: 8 is mapped to 'resolution-down'
  Button: 9 is mapped to 'button 5'
  Button: 10 is mapped to 'button 4'
  Button: 11 is mapped to UNKNOWN
  Button: 12 is mapped to UNKNOWN
  Button: 13 is mapped to UNKNOWN
  Button: 14 is mapped to UNKNOWN
  Button: 15 is mapped to UNKNOWN
  Button: 16 is mapped to 'profile-up'
  Button: 17 is mapped to 'profile-down'
Profile 2:
  Name: n/a
  Report Rate: 1000Hz
  Resolutions:
    0: 800x800dpi (active)
    1: 1600x1600dpi
    2: 3200x3200dpi
    3: 6400x6400dpi
    4: 8200x8200dpi
  Button: 0 is mapped to 'button 1'
  Button: 1 is mapped to 'button 2'
  Button: 2 is mapped to 'button 3'
  Button: 3 is mapped to 'button 4'
  Button: 4 is mapped to 'second-mode'
  Button: 5 is mapped to 'wheel-up'
  Button: 6 is mapped to 'wheel-down'
  Button: 7 is mapped to 'resolution-up'
  Button: 8 is mapped to 'resolution-down'
  Button: 9 is mapped to 'button 5'
  Button: 10 is mapped to 'button 4'
  Button: 11 is mapped to UNKNOWN
  Button: 12 is mapped to UNKNOWN
  Button: 13 is mapped to UNKNOWN
  Button: 14 is mapped to UNKNOWN
  Button: 15 is mapped to UNKNOWN
  Button: 16 is mapped to 'profile-up'
  Button: 17 is mapped to 'profile-down'
Profile 3:
  Name: n/a
  Report Rate: 1000Hz
  Resolutions:
    0: 800x800dpi (active)
    1: 1600x1600dpi
    2: 3200x3200dpi
    3: 6400x6400dpi
    4: 8200x8200dpi
  Button: 0 is mapped to 'button 1'
  Button: 1 is mapped to 'button 2'
  Button: 2 is mapped to 'button 3'
  Button: 3 is mapped to 'button 4'
  Button: 4 is mapped to 'second-mode'
  Button: 5 is mapped to 'wheel-up'
  Button: 6 is mapped to 'wheel-down'
  Button: 7 is mapped to 'resolution-up'
  Button: 8 is mapped to 'resolution-down'
  Button: 9 is mapped to 'button 5'
  Button: 10 is mapped to 'button 4'
  Button: 11 is mapped to UNKNOWN
  Button: 12 is mapped to UNKNOWN
  Button: 13 is mapped to UNKNOWN
  Button: 14 is mapped to UNKNOWN
  Button: 15 is mapped to UNKNOWN
  Button: 16 is mapped to 'profile-up'
  Button: 17 is mapped to 'profile-down'
Profile 4:
  Name: n/a
  Report Rate: 1000Hz
  Resolutions:
    0: 800x800dpi (active)
    1: 1600x1600dpi
    2: 3200x3200dpi
    3: 6400x6400dpi
    4: 8200x8200dpi
  Button: 0 is mapped to 'button 1'
  Button: 1 is mapped to 'button 2'
  Button: 2 is mapped to 'button 3'
  Button: 3 is mapped to 'button 4'
  Button: 4 is mapped to 'second-mode'
  Button: 5 is mapped to 'wheel-up'
  Button: 6 is mapped to 'wheel-down'
  Button: 7 is mapped to 'resolution-up'
  Button: 8 is mapped to 'resolution-down'
  Button: 9 is mapped to 'button 5'
  Button: 10 is mapped to 'button 4'
  Button: 11 is mapped to UNKNOWN
  Button: 12 is mapped to UNKNOWN
  Button: 13 is mapped to UNKNOWN
  Button: 14 is mapped to UNKNOWN
  Button: 15 is mapped to UNKNOWN
  Button: 16 is mapped to 'profile-up'
  Button: 17 is mapped to 'profile-down'
```
Launching Piper with the ratbagd still running shows a 404-mouse (device image seems to be missing - perhaps again some driver name mixup) but otherwise lists profiles and allows me to switch resolutions. 
Side note: ratbagctl lists zero LEDs on the Kone Pure (which should have one).

**Comment by stephanlachnit** [comment]
That looks promising! I'll check the compile time warnings later, at least some of them are normal.

The 404 screen is due to the missing USB-ID in Piper, you can check the PR there if you want to test that.

I think the 18 buttons are documented in the driver, I'll have to take a look^^

**Comment by stephanlachnit** [comment]
I compared your compile log with the master branch, and the warnings are exactly the same. However, you didn't compile everything, (with a fresh build directory I get 72 Objects, you only got 64, so some of them got compiled earlier). Can you try to remove your build directory entirely, build again and then try to run `ratbagctl.devel`?

Regarding the buttons:
https://github.com/libratbag/libratbag/blob/0c64dad9e1161f69077f173fe69a09fb0a8cfce7/src/driver-roccat-kone-pure.c#L109-L128

Regarding the svg: https://github.com/libratbag/piper/pull/540

Regarding the LEDs: the person who wrote the driver eventually stopped working on it, but there is a wiki with some information: https://github.com/hipnoizz/libratbag/wiki/Roccat-Kone-Pure
In this wiki is information about the LEDs, but it's not implemented. If you want, you can try to implement it yourself.

**Comment by zylxpl** [comment]
Hi everyone, what is the state of this commit, when it can be merge?

**Comment by stephanlachnit** [comment]
> Hi everyone, what is the state of this commit, when it can be merge?

When it's tested and confirmed working. If you have this mouse, you can go ahead and test it.

**Comment by zylxpl** [comment]
I have this mouse. Is there need to compile this or there are some binaries rady?

**Comment by stephanlachnit** [comment]
> I have this mouse. Is there need to compile this or there are some binaries rady?

You need to compile it yourself.

**Comment by Vectrex** [comment]
Sorry for not contributing any further after starting this issue. I will try to compile it asap.

**Comment by zylxpl** [comment]
Ok, finally have some time to play with it. And it looks very promising. Almost everything work as expected with mouse, no major issues.
What doesn't work:
- LED
- Mapping in piper "second mode" buttons, but that's piper issue, it works flawlessly from ratbagctl.

Anything else i can do?

image

**Comment by FFY00** [comment]
> Mapping in piper "second mode" buttons, but that's piper issue, it works flawlessly from ratbagctl.

Uh, could you open an issue for this? Thanks :blush:

**Comment by stephanlachnit** [comment]
@FFY00 should we merge this then? Afaik nobody is working on the LED support for this driver anyway. Maybe we got it to work if #1003 unites the Roccat drivers.

**Review by FFY00 — APPROVED** [review]
Sorry for the delay.

**Pull request merged**
