### PR TITLE
meson: bump project version to 0.9.906

### PR DESCRIPTION
**Pull request by FFY00**
Signed-off-by: Filipe Laíns <lains@archlinux.org>

### CODE REVIEW

**Comment by FFY00** [comment]
@whot can you just quickly approve the changes? I can't override that.

**Comment by whot** [comment]
Done. I thought you could directly push to master anyway?

**Comment by FFY00** [comment]
No, I can't. I don't have permission.

**Comment by whot** [comment]
You should have now. And if not I'm not sure what checkbox is missing :)

**Comment by FFY00** [comment]
I don't think I am gonna check that. It will stay a surprise :laughing:.

**Pull request merged**
