### PR TITLE
data: added Logitech G603 svg

### PR DESCRIPTION
**Pull request by zacjor**
Added a proper SVG for the Logitech G603 as requested in https://github.com/libratbag/libratbag/pull/505

Sorry if this was submitted improperly, I'm still pretty new to using git.

### CODE REVIEW

**Comment by zacjor** [comment]
Looks like there are still a few changes I need to make to the SVG. For one thing, the LED under the middle button is not configurable so I'll add it to the device layer. Second, I messed up the left and right click and center button. I should have those fixed in a moment.

**Comment by Hjdskes** [comment]
> Edit: Correction, it is the LED/Logo that I'm having issues with, not the LED under the middle button. On the G603 it's just a printed logo and not an LED. Should I just remove the logo from the SVG completely in this case?

When I look at other (Logitech) devices, I see that the [G300](https://github.com/libratbag/libratbag/blob/master/data/gnome/logitech-g300.svg) and [G9](https://github.com/libratbag/libratbag/blob/master/data/gnome/logitech-g9.svg) also show the "logo" while this isn't an LED.

On the other hand, the [G500](https://github.com/libratbag/libratbag/blob/master/data/gnome/logitech-g500.svg), [G600](https://github.com/libratbag/libratbag/blob/master/data/gnome/logitech-g600.svg) and [G700](https://github.com/libratbag/libratbag/blob/master/data/gnome/logitech-g700.svg) have the logo on the device but not in the SVG.

@whot We should probably add something to the guidelines for this and make the SVGs consistent. Do you have a preference for one over the other?

**Comment by whot** [comment]
IMO it doesn't matter as long as we're reasonably consistent. The logo adds a bit of 'depth' to it, makes it look ever so slightly more real. but it's far from required.

And given that most users only have one mouse, it's fine if we're a tad inconsistent right now.

**Comment by zacjor** [comment]
@Hjdskes @whot I went ahead and removed the logo for the time being as I was having some issues with Inkscape. Otherwise, the SVG should be good to go.

**Pull request merged**
