### PR TITLE
data: add a test for duplicate DeviceMatch lines

### PR DESCRIPTION
**Pull request by whot**
This MR will fail the tests because we currently have two duplicates:

- [ ] logitech-g700s-wireless.device and logitech-g700-wireless.device
- [ ] logitech-g900-wireless.device and logitech-g-pro-wireless.device (#579)

### CODE REVIEW

**Comment by whot** [comment]
I really don't know why this shows "all checks have passed" when they failed in circle ci...

**Comment by whot** [comment]
@FFY00 this check would be useful to have, we can drop the duplicates now, can't we? The g-pro is the lightspeed device now. The G700s seems like more of a worry though.

**Comment by FFY00** [comment]
Could you rebase this to `origin/master`? Should be fixed by now.

**Comment by whot** [comment]
The g700 and g700s still use the same match on the receiver, that needs to be fixed frist.

**Comment by FFY00** [comment]
Oh, then I don't think we are in any luck.

https://hansdegoede.livejournal.com/21731.html

I have one receiver but no mouse to connect it to. Someone needs to buy one of the old wireless mice (G700, G700s, G600, ... possibly others but I am not sure).

**Comment by whot** [comment]
well, our current situation is broken anyway because we'll always pick whichever comes first, so one of g700 or g700s already loses out anyway. The only sensible choice here is to pick the lowest common denominator (G700 iirc) and remove the other one - same effect but we're at least not pretending otherwise :)

And whoever has a G700s will just have to live with a semi-broken device and handle it with a local data file.

**Comment by FFY00** [comment]
But we don't support local data files. They would have to edit the system one.

**Comment by whot** [comment]
yeah, but... eh? it's not like anything really changes from the current situation, right now you have to delete the other file to make sure you get the right one.

**Comment by FFY00** [comment]
Still a better user experience IMHO, but if you want to do that go ahead, it doesn't matter that much.

**Comment by whot** [comment]
it's not documented anywhere and I only know about it because of this failing test here. So I'm not sure that classifies as user experience (well, not positive one anyway). And honestly, I don't even know which one of the two it picks because it depends on the order of data files loaded and whether we append or prepend those into a list (or hashtable?). So right now, it's effectively unpredictable anyway. Anyway, I also punted this to @bentiss yesterday because he has one of those devices. So what I'll do for this PR is drop one, merge the duplicate check, then @bentiss can add the other one again once the kernel support is there.

**Comment by whot** [comment]
admin superpowers! merged.

**Pull request merged**
