### PR TITLE
Additional identifier for MX Vertical

### PR DESCRIPTION
**Pull request by EduardoRFS**
```sh
$ egrep "Name|Handlers" /proc/bus/input/devices | egrep -B1 'Handlers.*mouse'
N: Name="Logitech MX Vertical"
H: Handlers=sysrq kbd leds event22 mouse0

$ lsusb
Bus 001 Device 005: ID 046d:c52b Logitech, Inc. Unifying Receiver
```

### CODE REVIEW

**Comment by FFY00** [comment]
That is the ID of the receiver, not the device. Which Linux version are you running (`unam -a`)?

**Comment by EduardoRFS** [comment]
```sh
Linux archlinux 5.12.3-arch1-1 #1 SMP PREEMPT Wed, 12 May 2021 17:54:18 +0000 x86_64 GNU/Linux
```

It works after the patch here. And this is the only Logitech device showing up on my lsusb

**Comment by FFY00** [comment]
If we add the ID for the receiver we have no way to tell devices apart, because devices might use the same receiver ID. It also won't work properly if you have multiple devices connected to the same receiver.

What shows up in lsusb does not matter that much, please try lshid.
https://pypi.org/project/lshid/

**Comment by EduardoRFS** [comment]
Got it

```sh
Device /dev/hidraw14: ID 046d:c08a Logitech MX Vertical Advanced Ergonomic Mouse
Device /dev/hidraw13: ID 046d:c08a Logitech MX Vertical Advanced Ergonomic Mouse
Device /dev/hidraw9: ID 046d:c08a Logitech MX Vertical Advanced Ergonomic Mouse
Device /dev/hidraw8: ID 046d:407b Logitech MX Vertical
Device /dev/hidraw7: ID 046d:c52b Logitech USB Receiver
```

**Comment by FFY00** [comment]
Okay, looks like the device you want is already there! It's `046d:407b`. If it is not already being detected by ratbagd, please open an issue containing the log from `ratbagd --verbose=raw` so that we can figure out what is wrong.

**Pull request closed without merging**
