### PR TITLE
Support MX Anywhere 2

### PR DESCRIPTION
**Pull request by hexchain**
Tested: device info, get/set DPI, remap button

Possible problem: "report rate" always says 0Hz - maybe mouse does not support this feature?

Still needed: an SVG of the device

Pictures of the device (found at https://support.logitech.com/en_us/product/mx-anywhere2):

Pressing the wheel does not seem to generate any event, it just switches between free/click mode, probably purely mechanically.

The square button in the middle is a "Gesture Button" by definition, but it is actually middle button by default, so I just set the button type to "middle button". The problematic button (https://github.com/libratbag/libratbag/issues/558#issuecomment-439732655) does not seem to be present on the device, although it has the `task_id` of "Gesture Button".

Some information about the device is inferred from XML files of a LogiOptions windows app installation. They are at `<somewhere>/LogiOptions/Software/Current` (I don't quite remember the leading path, sorry).

Please tell me if anything is wrong.

### CODE REVIEW

**Comment by hexchain** [comment]
Rebased to remove an unrelated commit.

**Comment by hexchain** [comment]
I've tried my best to draw the picture of the mouse, however my artistic skill can only go so far. It would be better if someone more talented can take a look at the SVG and possibly apply some fix to it.

**Comment by hexchain** [comment]
Changing report rate in Piper actually works, and can be read verified by `ratbagctl info eventXX`. I have no idea why it reported 0Hz at first, though...

**Comment by Hjdskes** [comment]
> I've tried my best to draw the picture of the mouse, however my artistic skill can only go so far. It would be better if someone more talented can take a look at the SVG and possibly apply some fix to it.

I think it looks great!

**Comment by hexchain** [comment]
If you look closely at the left part (near the extra buttons) you'll find something wrong, but I don't know how to fix that... :-)

**Comment by Hjdskes** [comment]
Can you show this on a screenshot? I don't have this device so it's hard testing.

**Comment by hexchain** [comment]
> If you look closely at the left part (near the extra buttons) you'll find something wrong, but I don't know how to fix that... :-)
I mean, that part on SVG does not look really similar to the photo.

**Comment by Hjdskes** [comment]
Oh, I see what you mean now. I think this is a minor issue only, as the image still easily maps to the real device so it serves its need well. It shouldn't have to hold back the PR ;)

**Comment by hexchain** [comment]
I did some more testing, mainly about the report rate.

Start `ratbagd` after connecting the device:
```
$ ratbagctl rate get event21
0
$ ratbagctl rate get-all event21
500
$ ratbagctl rate set 800 event21
$ ratbagctl rate get event21
800
$ ratbagctl rate get-all event21
500
```
It seems that device report rate is changed inside `ratbagd` even if the device does not support it (i.e. no `HIDPP_PAGE_ADJUSTABLE_REPORT_RATE`). Should it be better to also have a ratbag capability for this HID++ feature?

**Comment by whot** [comment]
I fixed the conflicts in the web UI but I'd rather have you rebase the branch so we can merge it nicely. The only conflict is in meson.build and that's simple enough to fix (reshuffling of the file names). Ping me when you've rebased and I'll click the magic merge button (or someone else can if they beat me to it)

**Comment by hexchain** [comment]
Thank you @whot! I've rebased against current master.

**Comment by whot** [comment]
I've squashed the commits for the .device and .svg files together with the meson build fix and pushed it directly as the series leading up to abe99fec6adaa224ec8d14e21fc7e3bf6b4c1991. This way we don't have half-working commits in the history.

This was faster than requesting another rebase, etc. sorry.

Closing this commit as the content is merged now, if not the branch as-is. Thanks!

**Comment by hexchain** [comment]
Thank you!

**Pull request closed without merging**
