### PR TITLE
Support for Roccat Kone Pure Optical Black/White Edition

### PR DESCRIPTION
**Pull request by hipnoizz**
WARNING: Do not merge, it will break support for Roccat Kone XTD.

I'm working on adding support for Roccat Kone Pure, specifically Optical Black/White Edition. Before I proceed further I would like some advice in a few areas.

Generally I wanted to take this approach:
1. Change `roccat` driver so it can handle both Kone XTD and Kone Pure (is there anyone that can validate my changes using XTD?).
2. Migrate the driver to new structure with `commit()` function.
3. Add support for additional features already supported by ratbag (e.g. LEDs, as I have a working prototype already).

The draft pull request visualizes changes that I needed to make to handle Kone Pure mouse. On one hand it borks existing support for Kone XTD. On the other hand it shows how both these mice differ.

1. My first question is how to tell the driver which mouse model he needs to communicate with. I saw two examples in the existing codebase - the `steelseries` driver uses `DeviceVersion` property (1, 2, 3...) and the `hidpp10` driver uses `ProfileType` property (e.g. G700). I'm not sure why there are already have two different properties already. Unfortunately I would prefer a property named `DeviceModel` as `ProfileType` is confusing due to the primary meaning of profiles as a set of configuration values. Thoughts?

2. Some differences between Pure and XTD could be described in the device files, e.g. `DpiRange` (100:5000@50 vs 200:8200@50), maybe number of buttons as well.

3. More serious are remaining differences, namely a) different data structures (USB HID GET/SET_REPORT) and button mappings. One way to handle that is to introduce additional structures (e.g. rename `roccat_settings_report` to `roccat_settings_report_kone_xtd` and then add a slightly different `roccat_settings_report_kone_pure`) and use conditions (if-oriented-programming ;-)) to handle different devices - there are like around 10 places like that. I would probably introduce several helper functions as some existing functions like `roccat_read_profile()` are already pretty lengthy. Any better ideas? Note that adding support for more Roccat devices would probably require to push further in that direction, as even XTD Optical seems to differ from 'common' XTD (https://github.com/libratbag/libratbag/issues/421).

I started documenting Kone Pure protocol here: https://github.com/hipnoizz/libratbag/wiki/Roccat-Kone-Pure if someone is interested. Some of this found it's place in the codebase, but not everything, so I think it is a worthwhile addition anyway.

### CODE REVIEW

**Comment by whot** [comment]
> is there anyone that can validate my changes using XTD

I have an XTD, ping me if you need specific testing. I'm also severely ETIME all the time though...

> how to tell the driver which mouse model he needs to communicate with.

Exactly like you describe. Those properties are purely implementation-defined and we can change them at will, whenever we feel like it. Pick what you feel comfortable with. `DeviceModel` can be iffy if you have multiple models sharing the same firmware, but as I said, we can change it anytime anyway.

> Some differences between Pure and XTD could be described in the device files

Yep, that would make sense

>  I would probably introduce several helper functions [...]

What we did for HID++ was to write protocol-only files (`hidpp10.c` and `hidpp20.c`) and then a separate driver that uses that protocol (`driver-hidpp10.c` and `driver-hidpp20.c`). Since not all devices support all bits of the protocol, this makes the driver easier to read. I think this approach should work for roccat devices too.

**Comment by bentiss** [comment]
In addition to what @whot said, there is no need to over engineer the device file and try to make it really generic.
We do have generic Logitech device files, because we know well their protocols and we can write one properly. For device we feel uncomfortable having a common driver, there is nothing wrong adding a new one. For example, the Logitech G300 and G600 are similar but completely separated. This avoids having to make device comparisons and keep the drivers simpler.

So one solution could be to rename `driver-roccat.c` into `driver-roccat-kone-xtd.c` and have your as `driver-roccat-kone-pure.c`. This way you could have your driver quicker upstream and collect all of the fame and bug reports from various users :)

And just to add more water here, the drivers and the device files are pure internal component, we do not care about ABI and we can rename whatever we want. So feel free to use the simpler solution for you, and refine it later when time permit.

**Comment by stephanlachnit** [comment]
@whot @FFY00 Since this is bascially merged and there's is no development here I can be closed I guess. But maybe @hipnoizz's wiki link should be noted somewhere? Could be either in the wiki or in the driver itself as a comment.

**Comment by FFY00** [comment]
I think we can come back here if needed.

**Pull request closed without merging**
